### PR TITLE
ES input PS3 GamePad Default Controller Assignment Fix.

### PR DESCRIPTION
**Pull request by Langerz82**
ES input PS3 GamePad Default Controller Assignment Fix.

### CODE REVIEW

**Comment by shantigilbert** [comment]
Why is this a WIP PR? what is missing?

**Comment by Langerz82** [comment]
Oh I was just making sure it's correct before submitting the PR, I noticed it also has a record in emuelec-addons, does that need to be changed too?

**Comment by Langerz82** [comment]
@shantigilbert I'm not sure that the user has entered the correct mapping. I will have to test this myself with a working PS3 Controller.

**Comment by shantigilbert** [comment]
The addon is not needed but it does not hurt to update it, if it's the correct info.

**Comment by shantigilbert** [comment]
The PS3 GUID 050000004c0500006802000000800000 already exists on the gamecontrollerdb.txt file 

https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L1350


You need to remove it first: https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/tools/sysutils/SDL_GameControllerDB/package.mk#L16

**Comment by Langerz82** [comment]
Removed stale record in gcdb.txt.

**Comment by Langerz82** [comment]
can commit.

**Pull request merged**
