### PR TITLE
Dev yabasanshiro sa joy fix

### PR DESCRIPTION
**Pull request by Langerz82**
If it cant find gamepad controller config then check the es_temporaryinput record and copy across if it exists.

### CODE REVIEW

**Comment by Langerz82** [comment]
can commit.

**Comment by shantigilbert** [comment]
Hmmm the file `es_temporaryinput.cfg` only exists when setting up a game controller and it only has the info for one controller, is this what you meant to do? 
why not just use the real `es_input.cfg` ?

**Comment by Langerz82** [comment]
Ah yes you are right it only configs one controller. What I might do is make an auto_gamepad file for this emulator. It passes the joypad name so fixing it should be relatively easy.

**Comment by Langerz82** [comment]
Close this, as not needed.

**Pull request closed without merging**
