### PR TITLE
Dev joy common cache fixes

### PR DESCRIPTION
**Pull request by Langerz82**
Fixes auto gamepad generation, when cache is enabled. So you don't have to configure the joypads everytime. If a joystick is different then it will re-create the joypad entry. These changes make sure that the old values get removed properly.

Tested and working.

### CODE REVIEW

**Comment by Langerz82** [comment]
Hang on, forgot to check mupen64plus joypad script.

**Comment by Langerz82** [comment]
Mupen64plus SA works fine too.

**Comment by Langerz82** [comment]
Ready for commit.

**Comment by shantigilbert** [comment]
I do not have the time to test it, so I trust you

**Comment by shantigilbert** [comment]
@Langerz82 Can you if possible add dpad to fbneosa auto gamepad? it works fine but the dpad is never configured.

**Comment by shantigilbert** [comment]
@Langerz82 can you explain what "Cache" does in gamepad autoconfig ? and why is it needed?

**Comment by Langerz82** [comment]
hey, if the players controller config is the exact same then it skips the process of editing the files to make them work with the controller. If it detects a difference with any of the controllers then clean_pad and set_pad will be called for that controller. It makes launching the games a little bit faster rather than automatically editing them all the time. But the edit process is pretty fast as it is. If you want cacheing to be enabled for that auto config then you have to be careful and make sure clean_pad only deletes the configs needed for that specific controller and no other controller configs.

**Comment by shantigilbert** [comment]
Some users are reporting issues when cache is enabled, I really don't think the half a second it takes to configure the gamepad is worth the hassle, or is it that much of a difference?

**Comment by Langerz82** [comment]
If it's causing probs best to default it to disabled. Yeah I agree the time is neglible if people are having input problems.

**Pull request merged**
