### PR TITLE
Add some missing file extensions to es_systems

### PR DESCRIPTION
**Pull request by Christoffer-Cortes**
- m3u added to dreamcast, msx and msx2
- 7z added to nds

### CODE REVIEW

**Comment by shantigilbert** [comment]
You personally tested these extensions?

**Comment by Christoffer-Cortes** [comment]
Yes, I've added them manually to es_systems and tested them. Flycast has no problem opening m3u files in games like Headhunter and Shenmue etc. and m3u was also tested with bluemsx with the game Fray in Magical Adventure which is a 4 disc game. Also tested all my NDS roms with Drastic in 7z format.

**Comment by shantigilbert** [comment]
Thank you

**Comment by fabioL78** [comment]
Hi Shanti, since you're at it, please also add m3u extensions to Sega CD and Sharp X68000, every update I also have to add them manually. Certified they work :)
Thanks!

**Comment by shantigilbert** [comment]
> Hi Shanti, since you're at it, please also add m3u extensions to Sega CD and Sharp X68000, every update I also have to add them manually. Certified they work :)
> Thanks!

x68000 already has .m3u extension

**Pull request merged**
