### PR TITLE
Check resolution fixes, Setres overhaul, cvbs fix other resolutions people could not see. Borders option added. AdvMame Exit Display Fix.

### PR DESCRIPTION
**Pull request by Langerz82**
Ok I overhauled the setres script. Resolutions with double numbers ex: 800x600p60hz, The 60HZ should now be outputting correctly as previously it was faulty.

UPDATED: Ok so I simplified the code a bit. If you want to add a windowed border to the screen in emuelec.conf you have to add the value "ee_videowindow" too and give it 4 or 2 numbers separated by a space. For instance ee_videowindow=50 50 1180 620.

**I'll explain the numbers.** 

Parameter 1 is the X pixel on the screen from the start horizontally (across the screen).
Parameter 2 is the Y pixel on the screen from the start vertically (down the screen).  

_If only 2 parameters are supplied it will adjust the screen uni-formally which means it will essentially keep the screen dimension but just squash the image. Useful if you want a even border around the screen display._

Parameter 3 is the Width in pixels you want the screen display box to be horizontally.
Parameter 4 is the Height in pixels you want the screen display box to be vertically.

So for example if I wanted the bottom to cut out a bit I could supply this to a 1280x720 screen:
In /emuelec/configs/emuelec.conf - add:
```
ee_videowindow=0 0 1280 620
```
And it should cut some of the bottom away.

If I wanted to add a 50 pixel border around the screen I'd use:
```
ee_videowindow=50 50
```

This should also fix allot of bugged resolutions some people have been having. If they have a bug res and they need to test copy this setres.sh into /emuelec/bin directory and it will be used instead by default.

This also fixes AdvMame Display Buffer Corruption Bug. In tandem with PR from GPTOKEYB:
https://github.com/EmuELEC/gptokeyb/pull/14

Continuation from PR:
https://github.com/EmuELEC/EmuELEC/pull/1015
https://github.com/EmuELEC/EmuELEC/pull/991
https://github.com/EmuELEC/EmuELEC/pull/955

### CODE REVIEW

**Comment by Langerz82** [comment]
This has to be tested thoroughly so I think it should be placed in 4.7. Putting in 4.6 and rushing things is not a good idea because this has significant changes and all emulators and ports need to be tested properly.

**Comment by Langerz82** [comment]
**Testing Procedures:**
_Make sure you are using the updated gptokeyb code here:_
https://gist.github.com/Langerz82/5fc2577f1e1e933d188368ad0ea2a60f

**Things to test:**
- Make sure resolution switches are clean and that screen gets properly blanked before switching resolutions.
- When no resolution switching is needed that the screen does not flicker.
- Check that all standalone emulators do not create pixel corruption and leave without a black buffer when exiting out of the applications.
- Make sure Emulator processes are cleanly exited, and that they have time to exit without calling kill -9 which is a hard force kill.
- Check resolutions in Emulation Station are correct and that you can change them.
- Report any resolution issues, such as screen blanking or screen corruption when selecting a valid mode.
- Resolution switching in ES should now be able to take effect just by restarting ES, no need to do a full reboot.
- Selecting native videos other than the current resolution in emulators work fine, and switching is correct (screen blanking should always occur in switching).
- Check that loading emulators and exiting still works fine even when loading splashes is disabled.

**Comment by Langerz82** [comment]
I'm waiting on a HDMI to AV cable to I can set the right cvbs window offsets for this change.

**Comment by Langerz82** [comment]
Ready to commit.

This PR also needs gptokeyb updated see:
https://github.com/EmuELEC/gptokeyb/pull/14

**Review by shantigilbert — APPROVED** [review]

**Comment by shantigilbert** [comment]
Thank You!

**Pull request merged**
