### PR TITLE
[AdvanceMame][game controller config] Sets joystick configuration automatically. (REVISED)

### PR DESCRIPTION
**Pull request by Langerz82**
DO NOT COMMIT OR REVIEW AS STILL NEEDS FIXING. I NEED TO TEST THAT ITS WORK OK TOO ON MY 2 DIFFERENT CONTROLLERS!!!

### CODE REVIEW

**Comment by Langerz82** [comment]
@shantigilbert 
As far as I can tell, I searched the gamecontrollerdb.txt for hat values, and I think only h0.1, h0.2, h0.4, h0.8 are the only hat values. If in SDL they all register as the same button code as my ps3 generic controller, then the fixes and additions are good. I don't have other controllers to test though so I can't be certain. We will have to look at it by case-by-case if they don't work. But yeah I'm making the scripts be able to change the hat SDL code in emuelec.conf should the need arise. The exception is the dolphin script, because it does not need a hat value for the auto gen.

**Comment by shantigilbert** [comment]
Please let me know when this is ready to test and I can test it with a few gamepads.

**Comment by Langerz82** [comment]
this change looks fucked, on hold. I'm too drunk atm to change things haha.

**Comment by Langerz82** [comment]
yeah, Im still too drunk lol need sleep, will test more tomorrow.

**Comment by Langerz82** [comment]
Ready for testing, should work ok.

**Comment by Langerz82** [comment]
actually put on hold I made an adjustment.

**Comment by Langerz82** [comment]
ok ready to test, I'm so tired lol ill test later on.

**Comment by shantigilbert** [comment]
Please just test this on your branch, I can't follow all the changes and the emails are driving me crazy. Once you have it tested on your branch and its ready for public testing please reopen the PR. This goes for all of them.

**Comment by Langerz82** [comment]
@shantigilbert 
lol ok. Ideally id like to read the mapping values from gamecontrollerdb.txt and not from the temp files. I might convert this later on when I've had some rest, I will close the PR's for now and re-open them when ready.

**Comment by shantigilbert** [comment]
Ok, Thanks. I just can't keep up with the changes and there is no point in me testing if it changes every few hours.

**Comment by Langerz82** [comment]
@shantigilbert 
No problem man, I'm using several branches so I have to commit or stash to switch branches, I've never used stash so I've been committing changes. I'll use stash from now on until I'm confident with the changes.

**Pull request closed without merging**
