### PR TITLE
[Fix][bluetooth] Fix for detecting when in an app so bluetooth searching disables.

### PR DESCRIPTION
**Pull request by Langerz82**
[Fix][bluetooth] Fix for detecting when in an app so bluetooth searching disables.

Haven't tested this yet, but I think it should work.

### CODE REVIEW

**Comment by Langerz82** [comment]
@shantigilbert I dont think this will include portmaster. Is there an init() and end() function for portmaster games? If not could we maybe implement one?

**Comment by shantigilbert** [comment]
What is this supposed to fix? has there been an issue I am not aware of?

**Comment by Langerz82** [comment]
@shantigilbert The script ordinarily while continue scanning unless emuelecRunEmu is called. However for ports it will continue running in the background without this patch.
The disabling of the bt-agent in emuelecRunEmu prob should be removed as the script should take care of disabling when running games. As some users might like to continue scanning if the have emuelec-bluetooth permanently running. Or if we must disable the agent then we should also do it for ports and do it in init_app_video() as that is called by both emuelecRunEmu and init_port.

However, this patch doesn't take into account launching portmaster games as I am not sure if there is any init() and end() functions.

**Comment by Langerz82** [comment]
@ebeem this modifies your code so you might like to take a look too.

**Comment by shantigilbert** [comment]
Wouldn't this be easier to just be called in the `event_game_start()` in combined scripts for ES? that way no other modification is needed, and you just need to kill the scanning process in the script, no?

**Comment by LEKSUS23** [comment]
В версии 4.6 не работает блютуз вообще! а в версии 4.7 работает блютуз но 2 джойстик не работает в играх, в меню настроек джойстик работает! Как решить проблему? В версии 4.5 - нет таких проблем? Тв бокс - A95X F3 Air (s905x3)

**Comment by LEKSUS23** [comment]
Bluetooth does not work at all in version 4.6! and in version 4.7, Bluetooth works, but the 2 joystick does not work in games, the joystick works in the settings menu! How to solve the problem? Is there no such problem in version 4.5? TV Box - A95X F3 Air (s905x3)

**Comment by Langerz82** [comment]
@shantigilbert Yes that would be a better way, I forgot about the script calls. Give me a few days and I'll make a new PR.

**Comment by LEKSUS23** [comment]
Ок

ср, 6 мар. 2024 г., 13:04 Joshua L ***@***.***>:

**Comment by Langerz82** [comment]
@LEKSUS23 your issue is unrelated to this PR, please go on discord and ask for help there.

**Comment by Langerz82** [comment]
@shantigilbert I tried moving the init_app_video function calls into the game-start script but the buffer corrupts when changing video. This PR fixes the issue of bt script halting during all games including portmaster however portmaster games cannot change video mode unless we have a script that calls init_port in between the ES halt and portmaster sh game call. Not a big deal for me, not sure it's that important for others either, but I know of not any other way.

**Comment by shantigilbert** [comment]
I don't understand your changes...  what I mean by using the scrip directly
e,g,  

```
	"game-start")
		event_game_start "${1}" "${2}" "${3}"
                killall emuelec-bluetooth
		;;
```

Any other changes are not needed 

any other video settings should be handled differently, as this PR is to fix(?) bluetooth 

if we need a way to signal when a game is running (which IMHO is already handled in the combined scripts) we should make changes to ES directly.

**Comment by shantigilbert** [comment]
if we need to make changes to ES we should do it here:

https://github.com/EmuELEC/emuelec-emulationstation/blob/329da6eaf2c38146cdfd3cf1930b0ebbe3ccecbd/es-app/src/FileData.cpp#L726
to create the /tmp file

and here to delete it
https://github.com/EmuELEC/emuelec-emulationstation/blob/329da6eaf2c38146cdfd3cf1930b0ebbe3ccecbd/es-app/src/FileData.cpp#L756

but again, this is already hadled by the scripting events, so I don't see the point

**Comment by Langerz82** [comment]
@shantigilbert essentially I'm trying to do two things at once since they are semi-related. Fix emuelec-bluetooth so it properly pauses which this patch adresses.

I'm also trying to work out a way to call init_app_video for all ports including those from Portmaster. I thought of a way using a halt.target es service, but for init_app_video I also need the platform and rom name variables. I can obtain them from game_start script but it's a little hacky to get the platform name.

killing emuelec-bluetooth isnt ideal as we are leaving the option for it to run permanently for users who want it to keep it running in the background. 
We shouldn't need to change ES, I would only do that as a last resort.

**Comment by Langerz82** [comment]
Don't need this PR if all ports and emus run through emuelecRunEmu. Will re-open if needed.

**Pull request closed without merging**
