### PR TITLE
show splash revised.

### PR DESCRIPTION
**Pull request by Langerz82**
show splash revised.

Needs testing.

### CODE REVIEW

**Comment by shantigilbert** [comment]
Can you elaborate a bit on what this fixes?

**Comment by Langerz82** [comment]
It works just like previous. The reason I changed the video conditionals to be part of the video code is if we add code it's a bit more cleaner. Your get_ee_setting for randomizing was a bit strange, it had a conditional in it so I'm not sure it was working properly. It's mainly just easier to read for people to make changes with, some indenting. And the start video having a check so it doesn't re-create the file every time.

**Comment by Langerz82** [comment]
When I copy the images to a pre-existing configured 4.2 the info "(Official - EmuELEC is FREE! NOT FOR SALE!):" comes up. But a fresh install does not show it. Is there something that changed it? They both use the same SYSTEM images so it must be my configuration.

**Comment by Langerz82** [comment]
Dont merge yet this either, it may need a small fix.

**Comment by Langerz82** [comment]
I didn't need to end up modifying this at all to work properly with set res, but lets wait a few days if it's going to be merged.

**Comment by shantigilbert** [comment]
> 
> 
> I didn't need to end up modifying this at all to work properly with set res, but lets wait a few days if it's going to be merged.

If its not needed I will just close the PR, no problem.

**Comment by Langerz82** [comment]
Yeah, it's not needed if we need to modify the splash the code the changes are saved here.

**Pull request closed without merging**
