### PR TITLE
Improved README.md layout & wording

### PR DESCRIPTION
**Pull request by GoliathLabs**
I have changed the layout of README.md to make it more visually appealing. I also changed the wording to make it easier to read and look more professional.

Feel free to leave some feedback :)

### CODE REVIEW

**Comment by shantigilbert** [comment]
Thanks you but as you can read here: 

```
EmuELEC is based on CoreELEC, which in turn is licensed under the GPLv2 (and GPLv2-or-later). All original files created by the EmuELEC team are licensed as GPLv2-or-later and marked as such.
```
But your changes say the license is unspecified. Please link it to `https://github.com/EmuELEC/EmuELEC/blob/master/licenses/GPL2.txt`

**Comment by GoliathLabs** [comment]
Yes, forgot to change the LICENSE path. Should be fixed by now.

**Comment by GoliathLabs** [comment]
You should still add a LICENSE file to the root of the repository, as the badge will change according to the file that is there

**Comment by shantigilbert** [comment]
Awesome, but can you please use https://shields.io/badge/license-GPL2-blue ?

**Comment by GoliathLabs** [comment]
Updated 😄

**Comment by shantigilbert** [comment]
Thanks for the changes!

**Pull request merged**
