### PR TITLE
retrorun fixes - initial commit

### PR DESCRIPTION
**Pull request by Langerz82**
retrorun fixes - initial commit.

I have a handheld so I'm making changes as I test them. These changes seem ok. It would help if someone with a Gameforce checked that it works fine too.

### CODE REVIEW

**Comment by Langerz82** [comment]
I got more fixes for this, but I will submit the changes another day. I'm kinda tired from working on the resolution shit lol.

**Comment by shantigilbert** [comment]
> I got more fixes for this, but I will submit the changes another day. I'm kinda tired from working on the resolution shit lol.

Thank you for the changes you have made, I appreciate them :)

**Comment by shantigilbert** [comment]
Any update on this? or is it ready for review?

**Comment by Langerz82** [comment]
You can review and commit this.

**Comment by Langerz82** [comment]
Properly reviewed, regarding the ES options not all working, in time I will add those features to ee-emulationstation.

**Comment by Langerz82** [comment]
@shantigilbert Can you change this back to a draft since it's only partially implemented? I don't think I can changed PR's back to a draft once I've changed it.

**Comment by Langerz82** [comment]
Let's close this. When I get time to add it's config options in ES we can re-open it.

**Pull request closed without merging**
