### PR TITLE
support for xbox360 usb gamepad

### PR DESCRIPTION
**Pull request by nwildner**
support for xbox360 usb gamepad

### CODE REVIEW

**Comment by nwildner** [comment]
already tested on my H96 Max x3 box. working as expected

**Comment by shantigilbert** [comment]
Can you also add the entry to the es_input.cfg file, otherwise this will get overwritten when someone does the gamepad configuration

**Comment by nwildner** [comment]
Hi @shantigilbert .

Done. Added xbox360 for `es_input.cfg` as well :)

Have a nice weekend.

**Comment by shantigilbert** [comment]
had to rever this, as the GUID is incomplete, I didn't notice that. please reopen with the complete GUID

**Pull request merged**
