### PR TITLE
implements installtointernal via a new package ampart

### PR DESCRIPTION
**Pull request by 7Ji**
I've written this partition tool in the past few days since ceemmc is closed-source and I'm not able to modify it for using in HybridELEC for partitioning the emmc. But this works for CoreELEC and EmuELEC perfectly fine.

With ampart, you can partition the emmc with a simple ``ampart /dev/mmcblk0 system::2G:2 data:::`` and achive installtointernal just like the good old days (of course you also need a script to invoke ampart and copying data, blah blah, as ampart is only a **partition tool**) and remove all the Android BS partitions

And it's written in **pure C**, in contrast to **ceemmc** which is basically a script faked as a C binary heavily relies on system() function to run other programs to do the work. So it's simple, fast, portable and powerful. It does all the work in **less than 0.1 second** and auto reload the partitions for you in one go. New partitions are immediately usable where **ceemmc** relies on losetup and new partitions won't even be usable before reboot.

The following is the new partition table after running the above command
````
==============================================================
NAME                          OFFSET                SIZE  MARK
==============================================================
bootloader               0(   0.00B)    400000(   4.00M)     0
  (GAP)                                2000000(  32.00M)
reserved           2400000(  36.00M)   4000000(  64.00M)     0
env                6400000( 100.00M)    800000(   8.00M)     0
system             6c00000( 108.00M)  80000000(   2.00G)     2
data              86c00000(   2.11G) 14b400000(   5.18G)     4
==============================================================
````

Currently I've only tested this package on BesTV R3300L (gxl_p212) and Xiaomi mibox3 (gxbb_p200) as these are the only devices in my hand that can run CoreELEC/EmuELEC

So, I would like **as many users test the partition tool as possible** to find out incompability issues, the binary releases for both x86_64 and arm platforms can be downloaded via the release page:
https://github.com/7Ji/ampart/releases/tag/v0.1

The tool works on both raw disk/reserved partition and image files dumped from them, you can play around with it on your x86_64 linux pc/servers first with image files and loop mounted images, then actually use it on your box to minimalize the risk.

### CODE REVIEW

**Comment by shantigilbert** [comment]
This sounds very interesting, do you have any example scripts to invoke the installtointernal, or did you use the one included in CE/EE?

**Comment by 7Ji** [comment]
A slightly modified old installtointernal should do the trick, I've added it in the package.
````
EmuELEC:~ # df -h
Filesystem                Size      Used Available Use% Mounted on
devtmpfs                483.5M      4.0K    483.5M   0% /dev
tmpfs                   195.5M      1.2M    194.3M   1% /run
/dev/system               2.0G   1009.2M      1.0G  49% /flash
/dev/loop0              988.0M    988.0M         0 100% /
/dev/data                 5.0G     23.5M      5.0G   0% /storage
tmpfs                   488.8M         0    488.8M   0% /dev/shm
tmpfs                     4.0M         0      4.0M   0% /sys/fs/cgroup
tmpfs                   488.8M      4.0K    488.8M   0% /var
tmpfs                   488.8M         0    488.8M   0% /tmp
none                      5.0G     23.5M      5.0G   0% /tmp/database
none                      5.0G     23.5M      5.0G   0% /tmp/cores
none                      5.0G     23.5M      5.0G   0% /tmp/assets
none                      5.0G     23.5M      5.0G   0% /tmp/joypads
none                      5.0G     23.5M      5.0G   0% /tmp/shaders
none                      5.0G     23.5M      5.0G   0% /tmp/overlays
````

**Comment by 7Ji** [comment]
Roms will still be mounted from the external drive due to the current mount_roms function does not check for bootup drive:
https://github.com/EmuELEC/EmuELEC/blob/0e939189579e2700e970e2eaaa89630cad2dd173/packages/sysutils/busybox/scripts/init#L705
But I guess this is even better as you can create an EEROMS partitions on the whole SD card and enjoy a internal system + external roms combination
````
EmuELEC:~ # df -h
Filesystem                Size      Used Available Use% Mounted on
devtmpfs                483.5M      4.0K    483.5M   0% /dev
tmpfs                   195.5M      1.2M    194.3M   1% /run
/dev/system               2.0G   1009.2M      1.0G  49% /flash
/dev/loop0              988.0M    988.0M         0 100% /
/dev/data                 5.0G    502.9M      4.5G  10% /storage
/dev/mmcblk1p3           25.5G      3.1M     25.5G   0% /storage/roms
/dev/mmcblk1p3           25.5G      3.1M     25.5G   0% /storage/.update
tmpfs                   488.8M         0    488.8M   0% /dev/shm
tmpfs                     4.0M         0      4.0M   0% /sys/fs/cgroup
tmpfs                   488.8M      4.0K    488.8M   0% /var
tmpfs                   488.8M         0    488.8M   0% /tmp
````

**Comment by 7Ji** [comment]
@shantigilbert 

I don't think formatting parittions with M$'s fs on an internal storage device that is impossible to be accessed like an USB drive/SD card would make much sense, so the script won't create an EEROMS partition on the emmc.

If users want plug-and-copy experience they can just format a dedicated SD card/USB drive as EEROMS which they can keep across multiple EmuELEC installations.

So the internal storage partitions would always be:
1. bootloader (reserved for u-boot)
2. reserved (reserved for partition table, dtb, etc)
3. env (reserved for u-boot envs)
4. system (would be passed as boot to kernel, mounted at /flash, contain stuffs similiar to EMUELEC partition on SD card)
5. data (would be passed as disk to kernel, mounted at /storage, contain stuffs similiar to STORAGE partition on SD card)

system+data can use all the space not occupied by the reserved partitions, basically size of emmc(/dev/mmcblk0) - 108M, nothing wasted on Android BS we don't want, not even Android boot logo.

WIthout any external drives containing EEROMS partitions plugged in, /storage/roms is a folder under /storage and share the capacity of data partition

With any external drives containing EEROMS partitions plugged in, /storage/roms will be mounted from one of these partitions (yeah, depending on luck, since mount_roms() mounts LABEL=EEROMS which will become tricky if multiple LABEL=EEROMS partitions exist), 

In the second situation, even if users just mess up with their installtion and need to reinstall EmuELEC, or even worse, flash a stock Android image to debrick, after installtointernal they can just plug the EEROMS SD card/USB drive and enjoy their roms and savestates, no backing up and restoring are needed

**Comment by shantigilbert** [comment]
> I don't think formatting parittions with M$'s fs on an internal storage device that is impossible to be accessed like an USB drive/SD card would make much sense, so the script won't create an EEROMS partition on the emmc.

This is how it was for CEEMMC as it makes no sense, the `STORAGE` partition was formatted for the rest of the space, like CoreELEC does it, and the `/storage/roms` folder would contain the ROMS 

The EEROMS is not needed at all for external USB roms, this is  already possible with any label just by creating a file. In fact I would recommend NOT to label the external usb as EEROMS.

If you are certain that this works as you and me describe it, then I can merge it!

**Comment by 7Ji** [comment]
Well I've modified the script again, so now when user's emmc is larger than 4G, they will be asked whether or not to create a dedicated EEROMS partition on emmc. But the EEROMS partition on the emmc will always be formatted with EXT4

**Comment by 7Ji** [comment]
So, take an 8G device for example, when user wants a dedicated EEROMS partition on emmc (default choice), the partition layout would be:
````
==============================================================
NAME                          OFFSET                SIZE  MARK
==============================================================
bootloader               0(   0.00B)    400000(   4.00M)     0
  (GAP)                                2000000(  32.00M)
reserved           2400000(  36.00M)   4000000(  64.00M)     0
env                6400000( 100.00M)    800000(   8.00M)     0
system             6c00000( 108.00M)  80000000(   2.00G)     2
data              86c00000(   2.11G)  80000000(   2.00G)     4
eeroms           106c00000(   4.11G)  cb400000(   3.18G)     4
==============================================================
````
The file system tree would be mounted like:
````
/dev/system /flash vfat ro,noatime,fmask=0022,dmask=0022,codepage=936,iocharset=utf8,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/loop0 / squashfs ro,relatime 0 0
/dev/data /storage ext4 rw,noatime,data=ordered 0 0
/dev/eeroms /storage/roms ext4 rw,relatime,data=ordered 0 0
/dev/eeroms /storage/.update ext4 rw,relatime,data=ordered 0 0
````

And when they don't, the partition layout would be:
````
==============================================================
NAME                          OFFSET                SIZE  MARK
==============================================================
bootloader               0(   0.00B)    400000(   4.00M)     0
  (GAP)                                2000000(  32.00M)
reserved           2400000(  36.00M)   4000000(  64.00M)     0
env                6400000( 100.00M)    800000(   8.00M)     0
system             6c00000( 108.00M)  80000000(   2.00G)     2
data              86c00000(   2.11G) 14b400000(   5.18G)     4
==============================================================
````
And the file system tree would be mounted like:
````
/dev/system /flash vfat ro,noatime,fmask=0022,dmask=0022,codepage=936,iocharset=utf8,shortname=mixed,utf8,errors=remount-ro 0 0
/dev/loop0 / squashfs ro,relatime 0 0
/dev/data /storage ext4 rw,noatime,data=ordered 0 0
````
The users can choose whatever they want.

**Comment by 7Ji** [comment]
@shantigilbert 
I guess you can merge it now, or would you like some changes in names or behaviours?

**Comment by shantigilbert** [comment]
> @shantigilbert I think you can merge it now, or would you like some changes in names or behaviours?

Thank you, You said you only tested this with a gxl_p212 and a gxbb_p200 device (although currently gxbb is no longer supported) Can you place a check on the script until we can test this with other SOCs? my concern is that if this would break devices with say S905x2,S905x3 or S922x since I know some people will try to use this.

**Comment by 7Ji** [comment]
@shantigilbert 
A check was added and installtointernal will refuse to run if device tree does not start with gxl_p212

**Comment by 7Ji** [comment]
> a gxl_p212 and a gxbb_p200 device

It was the partition tool **ampart** that was verified on these devices, not the install script, the install script was only verified on gxl_p212 since it does not work on non-ng devices' filesystem tree
ampart should work on all Amlogic gx devices as it's written against the meson-gx-mmc driver, which all of current -ng deivces use

**Comment by shantigilbert** [comment]
I might be confused... GXL is not part of the `NG` devices, those are only G12a, SM1 and G12B  (so s905x2, s905x3 and s922x/a311d) I am sorry if I am confusing you with the name "Amlogic-ng" 

So "ampart" is ONLY for gxl devices, right? Sorry for the dumb questions, I just want to fully understand how it works

**Comment by 7Ji** [comment]
It works on Amlogic emmc devices that have a partition table with magic **MPT** and version **01.00.00**, but Amlogic is just too lazy to update the format so basically all of the devices use this format (the never re-invent the wheel philosophy, yeah). You see /dev/data, /dev/system, /dev/env, etc? These are all created by [Amlogic's emmc driver](https://github.com/CoreELEC/linux-amlogic/blob/amlogic-4.9-19/drivers/amlogic/mmc/emmc_partitions.c) and the driver is used by all devices that run CoreELEC/EmuELEC with a linux-amlogic kernel.

It is not only for gxl devices, in theory it would work for ALL Amlogic devices, as long as there's no big change on the partition format, which you can check the driver and say a big YES. Even those not supported by CE/EE, even historically not supported (those old S8xx devices, those AML-8726 devices), should be supported. 

The reason I can only verify it on a gxl device was because all I have were two Amlogic boxes, one Xiaomi mibox3 (gxbb_p200) with a locked bootloader that forced me into creating HybridELEC, and one BesTV R3300L (gxl_p212) not supported by ceemmc that forced me to write a whole blown partition tool in a few days. I was never into development of Amlogic boxes so I got no development board and common boxes you would expect. So, it's not that tests on other devices failed, it's that I just can't test on other devices since I don't even have one.

**Comment by shantigilbert** [comment]
Awesome, thanks for the explanation, I have more devices I can test this on when I get time, I will go ahead and merge it anyways, now that the check is in place at least people that do not know what they are doing will not mess things up (hopefully!)

**Comment by 7Ji** [comment]
For mass tests for ampart I would recommend dumping the reserved partition
or the emmc disk and test on the dumpped image to check if it works. On a
beefy Linux machine with a fast SSD things will become easier as you can
copy to restore the backed up dumped images quicklier.

You need x86_64 build for this though, and I'm afraid you would need to
compile yourself as I've removed the binary releases.

Utilize --snapshot, the --clone option can be used at any time to easily
restore the part table to what it was using the args printed by snapshot.

Then after making sure ampart itself will work on the partition table, you
can test the ampart command included in the installation script and reboot
to check if altering the part table renders the whole device unusable
(ampart /dev/mmcblk0 system::2G:2 data::2G: eeroms:::)

I've added the function to auto rewrite env to the new location to ampart
but I can't remember correctly (sleepy, 2:08 AM here) if the version in the
package is the one with this function or not. So dd to backup and restore
env would be better

After making sure devices won't brick after part layout changed, you can do
the time-consuming installtointernal tests as now the new issues should
only be caused by the script, no ampart

Doing it this way would save so much time since the emmc is really slow and
you don't want to repeatedly write 1G to it


shantigilbert ***@***.***> 于 2022年5月23日周一 上午1:44写道：

**Comment by 7Ji** [comment]
@shantigilbert
Oops. found I left a space bar at the end of PKG_SHA256,  maybe you can just delete from your side without me opening another PR?
https://github.com/EmuELEC/EmuELEC/blob/b5aca266017b8b41ede966613ce7d9cc3def741d/projects/Amlogic-ce/packages/tools/ampart/package.mk#L6

**Comment by shantigilbert** [comment]
@7Ji do you use discord? if so please join us so we can discuss this in an easier way.

On to my tests, 
using a s905x3 device, while it seems that the partitioning works as it should the device does not boot: 

```
ampart /dev/mmcblk0
Path '/dev/mmcblk0' seems a device file
Path '/dev/mmcblk0' detected as whole emmc disk
Path '/dev/mmcblk0' is a device, getting its size via ioctl
Disk size is 61865984000 (57.62G)
Reading old partition table...
Notice: Seeking 37748736 (36.00M) (offset of reserved partition) into disk
Validating partition table...
Partitions count: 6, GOOD √
Magic: MPT, GOOD √
Version: 01.00.00, GOOD √
Checksum: calculated 1667e732, recorded 1667e732, GOOD √
Partition table read from '/dev/mmcblk0':
==============================================================
NAME                          OFFSET                SIZE  MARK
==============================================================
bootloader               0(   0.00B)    400000(   4.00M)     0	
  (GAP)                                2000000(  32.00M)
reserved           2400000(  36.00M)   4000000(  64.00M)     0	
env                6400000( 100.00M)    800000(   8.00M)     0	
system             6c00000( 108.00M)  80000000(   2.00G)     2	
data              86c00000(   2.11G)  80000000(   2.00G)     4	
eeroms           106c00000(   4.11G) d60c00000(  53.51G)     4	
==============================================================
Disk size totalling 61865984000 (57.62G) according to partition table
```
I ran the script twice and I noticed that the first time the EMMC was detected as 64G and the second time as 57.62G.

But the device does not boot, it just says: `Error in mount_sysroot: mount_commom: Could not mount /flash/SYSTEM`

**Comment by shantigilbert** [comment]
Now a third time and its detected as 58G `Oh great! You emmc is larger than 4G (58G)` but same error message, can't boot. Now if I use the SD card and run 
```
ampart /dev/mmcblk0
Path '/dev/mmcblk0' seems a device file
Path '/dev/mmcblk0' detected as whole emmc disk
Path '/dev/mmcblk0' is a device, getting its size via ioctl
Disk size is 61865984000 (57.62G)
Reading old partition table...
Notice: Seeking 37748736 (36.00M) (offset of reserved partition) into disk
Validating partition table...
Partitions count: 20, GOOD √
Magic: MPT, GOOD √
Version: 01.00.00, GOOD √
Checksum: calculated f55a57fc, recorded f55a57fc, GOOD √
Warning: Misbehaviour found in partition name 'cri_data':
 - Underscore (_) is used, this is not recommended as it may confuse some kernel and bootloader
Partition table read from '/dev/mmcblk0':
==============================================================
NAME                          OFFSET                SIZE  MARK
==============================================================
bootloader               0(   0.00B)    400000(   4.00M)     0	
  (GAP)                                2000000(  32.00M)
reserved           2400000(  36.00M)   4000000(  64.00M)     0	
  (GAP)                                 800000(   8.00M)
cache              6c00000( 108.00M)  46000000(   1.09G)     2	
  (GAP)                                 800000(   8.00M)
env               4d400000(   1.21G)    800000(   8.00M)     0	
  (GAP)                                 800000(   8.00M)
logo              4e400000(   1.22G)    800000(   8.00M)     1	
  (GAP)                                 800000(   8.00M)
recovery          4f400000(   1.24G)   1800000(  24.00M)     1	
  (GAP)                                 800000(   8.00M)
misc              51400000(   1.27G)    800000(   8.00M)     1	
  (GAP)                                 800000(   8.00M)
dtbo              52400000(   1.29G)    800000(   8.00M)     1	
  (GAP)                                 800000(   8.00M)
cri_data          53400000(   1.30G)    800000(   8.00M)     2	
  (GAP)                                 800000(   8.00M)
param             54400000(   1.32G)   1000000(  16.00M)     2	
  (GAP)                                 800000(   8.00M)
boot              55c00000(   1.34G)   1000000(  16.00M)     1	
  (GAP)                                 800000(   8.00M)
rsv               57400000(   1.36G)   1000000(  16.00M)     1	
  (GAP)                                 800000(   8.00M)
metadata          58c00000(   1.39G)   1000000(  16.00M)     1	
  (GAP)                                 800000(   8.00M)
vbmeta            5a400000(   1.41G)    200000(   2.00M)     1	
  (GAP)                                 800000(   8.00M)
tee               5ae00000(   1.42G)   2000000(  32.00M)     1	
  (GAP)                                 800000(   8.00M)
vendor            5d600000(   1.46G)  14000000( 320.00M)     1	
  (GAP)                                 800000(   8.00M)
odm               71e00000(   1.78G)   8000000( 128.00M)     1	
  (GAP)                                 800000(   8.00M)
system            7a600000(   1.91G)  80000000(   2.00G)     1	
  (GAP)                                 800000(   8.00M)
product           fae00000(   3.92G)   8000000( 128.00M)     1	
  (GAP)                                 800000(   8.00M)
data             103600000(   4.05G) d64200000(  53.56G)     4	
==============================================================
Disk size totalling 61865984000 (57.62G) according to partition table
```
The partitions seem all over the place.

**Comment by 7Ji** [comment]
There's a wierd glitch that after reboot, the part table would be reverted to what it was like before ampart modifies it
I'm debugging this right now after I updated the install scripts to support dual-boot mode (https://github.com/7Ji/HybridELEC/tree/ee-ampart-replica-ceemmc) and found the bug (the happiness becomes frustration that I was dropped into endless debugging).
Seems something wrong in the processing, I suggest you do not use ampart on real disk right now
I've also joined the EmuELEC discord server and send you a friend invitation.

**Comment by 7Ji** [comment]
Found it, it's because of the partitions node in the dtb, the u-boot would read the partitions from herre and reset the table according to the partitions in the dtb.  I'll update ampart  to remove the partitiions node

**Pull request merged**
