### PR TITLE
Update setres.sh

### PR DESCRIPTION
**Pull request by Langerz82**
Adjust setres to be the same as the 64-bit version with the minor BPP legacy code. The previous code was not very clean and may cause issues.

### CODE REVIEW

**Comment by shantigilbert** [comment]
> Adjust setres to be the same as the 64-bit version

Can you elaborate on this? what 64b version?

**Comment by Langerz82** [comment]
It's the same code that we currently have for aarch64 latest version. Just ported over and I included the legacy BPP code it once had.

**Comment by shantigilbert** [comment]
I just realized this is for the master_32bit branch, did you tested this? that branch is supposed to be frozen.

**Comment by Langerz82** [comment]
I'm compiling the project along with some minor show_splash changes, as that may be the cause of the freeze.

**Pull request closed without merging**
