### PR TITLE
emulator - duckstation standalone - game controller autoconfiguration

### PR DESCRIPTION
**Pull request by Langerz82**
This is a game controller autoconfiguration script for duckstation standalone.

Needs proper testing.

To enable:
1. SSH in and copy set_duckstation_joy.sh in /emuelec/bin.
2. Add duckstation_auto_gamepad=1 in emuelec.conf. like so:
```
echo "duckstation_auto_gamepad=1" >> /emuelec/configs/emuelec.conf
```
Good luck testing and thanks.

### CODE REVIEW

**Comment by Langerz82** [comment]
This can be commited. It will be disabled by default and if the users want to use it they can just add the above to emuelec.conf.

**Comment by shantigilbert** [comment]
> they can just add the above to emuelec.conf.

I think there should be a "feature/options" in ES to enable or disable this, like ADVMAME has, otherwise regular users will not be able to even test this.

**Comment by Langerz82** [comment]
Done, see: https://github.com/EmuELEC/emuelec-emulationstation/pull/68

**Comment by soulbrix** [comment]
Hi guys - I think this option is causing issues. I was using Duckstation standalone and my binding configurations kept being overwritten everytime I opened the emulator. I know it was something that happened at startup because I checked the configuration files myself and they saved the bindings - then they were overwritten at startup. I fixed the issue by setting that emuelec.conf option to 0. Now it seems like it's saving the bindings.

**Pull request merged**
