### PR TITLE
Port ikemen-go to the emuelec

### PR DESCRIPTION
**Pull request by Diegrosan**
**Summary of what was done:**
Added:

emuelecRunEmu.sh : Added emu ikemen
es_systems.cfg : Added system ikemen
es_features.cfg :  Added ikemen
emuelec-dirs.conf : Added ikemen
emuelec package.mk : Added ikemen-go
updated: go package.mk
Added ikemen-go + the ikemen theme for crystal : ikemen package.mk

The game folder must be inside 'roms/ikemen/game folder for ikemen'. The extension is merely symbolic to locate the game folder. Not all Ikemen games will work immediately. If they don't work at first, you will need to adapt them, as Linux is case-sensitive, unlike Windows. Despite this, it is quite functional.

**Tested on the S905x3, the port with SD2 and gles2, I believe with the others will work too.**

### CODE REVIEW

**Comment by Kelvfimer** [comment]
@Diegrosan I had to use git commit to make it work dda76beac02a884de867bf48e67b9ba24fe766f3. 
The Crystal theme at least for me was not working and I had to execute ir manually. I think it is need to ask the Crystal Theme developer to add it.
When playing the up hat button was not working so I couldn't jump. I had to use the analog left pad to jump.

**Comment by Diegrosan** [comment]
Thx! The theme script was just for testing; ideally, it should be integrated with the Cristal theme. As for the gamepad, the Xbox One and a similar one with an Xbox One driver were tested. I can't say how it would behave with other gamepads. If you have any questions, I'm available.

https://github.com/user-attachments/assets/f8cb3473-5a79-402f-8fe0-a605d3064506

**Comment by Kelvfimer** [comment]
I think is better if you remove the theme files and the logic around it and I will ping the Crystal Theme developer to have the theme. Here it is a video of it working on my side. BTW, It is a hell the case sensitive folders... https://www.youtube.com/watch?si=fhILHw5qgOZ7K0h3&v=CoQhDxA0jIA&feature=youtu.be

**Comment by shantigilbert** [comment]
@Diegrosan Thanks for the PR awesome work!. As @Kelvfimer pointed out, please remove the theme changes, because even if we merge it as is, it will not work as the theme name should be Crystal (its "cristal" in your pr)

Thank you!

**Comment by miwasp** [comment]
Is this (es_systems.cfg) a typo?
`extension>.ikemen .IREMEN .pc .PC .exe .EXE</extension> `

**Comment by Diegrosan** [comment]
> @DiegrosanObrigado pelo trabalho incrível de RP!. Como@Kelvfimerapontado, por favor remova as alterações do tema, porque mesmo se mesclarmos como está, não funcionará, pois o nome do tema deveria ser Crystal (é "cristal" no seu pr)
> 
> Obrigado!

Alright. I'm very happy that you liked it; I will fix the script.

**Comment by Diegrosan** [comment]
> @Diegrosan Thanks for the PR awesome work!. As @Kelvfimer pointed out, please remove the theme changes, because even if we merge it as is, it will not work as the theme name should be Crystal (its "cristal" in your pr)
> 
> Thank you!

Alright. I'm very happy that you liked it; I will fix the script.

**Comment by Diegrosan** [comment]
> Is this (es_systems.cfg) a typo? `extension>.ikemen .IREMEN .pc .PC .exe .EXE</extension> `

hello, Are these extensions correct: .ikemen, .IREMEN, .pc, .PC, .exe, .EXE? They are symbolic and will not be executed directly; they are just a pointer to locate the game's folder.

**Comment by shantigilbert** [comment]
Thank you!

**Comment by miwasp** [comment]
> > Is this (es_systems.cfg) a typo? `extension>.ikemen .IREMEN .pc .PC .exe .EXE</extension> `
> 
> hello, Are these extensions correct: .ikemen, .IREMEN, .pc, .PC, .exe, .EXE? They are symbolic and will not be executed directly; they are just a pointer to locate the game's folder.

I mean the upper case „IREMEN“, please note the ‚R‘, while lower case is „ikemen“ with ‚k‘.

**Comment by maskedeken** [comment]
Ikemen_Go got killed on S905x2. Here is the logs:

[main.go][main] Running at OS=[linux] ARCH=[arm64]
[main.go][setupConfig] NOT importing data/mugen.cfg
[main.go][setupConfig] Assigning Joystick setting to Engine
sys.joystickConfig[0] = [10 12 13 11 0 1 5 2 3 -12 7 4 -10 6]
sys.joystickConfig[1] = [10 12 13 11 0 1 5 2 3 -12 7 4 -10 6]
sys.joystickConfig[2] = [10 12 13 11 0 1 5 2 3 -12 7 4 -10 6]
sys.joystickConfig[3] = [10 12 13 11 0 1 5 2 3 -12 7 4 -10 6]
2024/11/19 22:02:00 GetCurrentDisplayMode: 1920x1080
Using OpenGL ES 3.2 git.c8adbf9.ad00b04c1b60847de257177231dc1a53 (Mali-G31)
Fullscreen: false (-1 x -1)
scrrect: 0,0 - 1280,720
gameWidth x gameHeight: 426,240
widthScale x heightScale: 3.004695,3
[main.go][main]: Running in lua script=[external/script/main.lua] using motif=[data/system.def]
[system_sdl.go][pollEvents] Using Joystick id=0 [HJC Game [ BETOP CONTROLLER ].linux.arm64.sdl]
	Total Button=12
	Total Axes=4
	Total Hats=1
	Config is NOT overwritten, using {0 10 12 13 11 0 1 5 2 3 -12 7 4 -10 6}
Killed

**Comment by Kelvfimer** [comment]
@maskedeken which game are u using? Remember you have to adjust the case sentiviness of the files and the folders defined on the lua files

**Comment by maskedeken** [comment]
> @maskedeken which game are u using? Remember you have to adjust the case sentiviness of the files and the folders defined on the lua files

this one [https://mugenguild.com/forum/topics/blazblue-battle-coliseum-arcade-versus-mode-199307.0.html](https://mugenguild.com/forum/topics/blazblue-battle-coliseum-arcade-versus-mode-199307.0.html)

**Comment by Kelvfimer** [comment]
@maskedeken it is not emuelec issue. Ikemen turns greedy and consume whole RAM and that crashes the board. I have odroid n2+ 4GB and it took the whole 4 GB and crashes. You should open an issue or contact the owner of https://github.com/leonkasovan/Ikemen-GO

**Comment by Kelvfimer** [comment]
Reconfirmed I tested the game in windows and it is a resource killer i had like 20 GB of RAM allocated for ikemen that's a lot... or the developer improve ram management or games that takes more than 3Gb will crash. As a recommendation test the game in windows and if consumes less than 3gb I will work on emuelec.

**Comment by Diegrosan** [comment]
> > > Isto (es_systems.cfg) é um erro de digitação?`extension>.ikemen .IREMEN .pc .PC .exe .EXE</extension> `
> > 
> > 
> > Olá, Essas extensões estão corretas: .ikemen, .IREMEN, .pc, .PC, .exe, .EXE? Elas são simbólicas e não serão executadas diretamente; elas são apenas um ponteiro para localizar a pasta do jogo.
> 
> Quero dizer, a letra maiúscula „IREMEN“, observe o ‚R', enquanto a minúscula é „ikemen“ com ‚k'.

sim

> > > Isto (es_systems.cfg) é um erro de digitação?`extension>.ikemen .IREMEN .pc .PC .exe .EXE</extension> `
> > 
> > 
> > Olá, Essas extensões estão corretas: .ikemen, .IREMEN, .pc, .PC, .exe, .EXE? Elas são simbólicas e não serão executadas diretamente; elas são apenas um ponteiro para localizar a pasta do jogo.
> 
> Quero dizer, a letra maiúscula „IREMEN“, observe o ‚R', enquanto a minúscula é „ikemen“ com ‚k'.



> > > Is this (es_systems.cfg) a typo? `extension>.ikemen .IREMEN .pc .PC .exe .EXE</extension> `
> > 
> > 
> > hello, Are these extensions correct: .ikemen, .IREMEN, .pc, .PC, .exe, .EXE? They are symbolic and will not be executed directly; they are just a pointer to locate the game's folder.
> 
> I mean the upper case „IREMEN“, please note the ‚R‘, while lower case is „ikemen“ with ‚k‘.

Now I understand, my native language is not English, so sometimes I need more details to understand. Sorry, but I appreciate the concern. I will correct it, thank you.

**Comment by Diegrosan** [comment]
> @Diegrosan did you manage to run SNK-vs-Capcom-EX https://www.dropbox.com/scl/fi/mmknj3b6y7umoip7me24s/SNK-vs-Capcom-EX-v0.7.7.7z?rlkey=bqpqr6j1bzy5jx6jbws1wbfoq&e=1&dl=0 ? I was making manual work on the lua files but it crashes when the fight starts? Pls can you take a look? thx

Alright, I’ll test it soon and get back to you about the game.

**Comment by Kelvfimer** [comment]
Cook thx @Diegrosan

**Comment by 25minutes** [comment]
Hey guys, thanks for adding Ikemen_Go. 
I manually compile it per https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/emulators/ikemen-go/package.mk and successfully get it running. However, it appears DPAD doesn't work properly (Left/Right/Down are fine but no response on UP). Analog is working btw. Do you experience the same issue?

**Comment by Kelvfimer** [comment]
> Hey guys, thanks for adding Ikemen_Go. I manually compile it per https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/emulators/ikemen-go/package.mk and successfully get it running. However, it appears DPAD doesn't work properly (Left/Right/Down are fine but no response on UP). Analog is working btw. Do you experience the same issue?
> 
> edit: My gamepad is in XINPUT mode, and gamecontrollerdb.txt contains correct info for it. All other emulators and port games are working fine.

Not Emuelec issue, I faced it. You must set up the pads in the setup files. Your pad must match the sdl joy settings and then you have to inut them in the config file. I don't have any ikemengo game not set up but let me some days and I will show you how to do it.

**Comment by 25minutes** [comment]
> Not Emuelec issue, I faced it. You must set up the pads in the setup files. Your pad must match the sdl joy settings and then you have to inut them in the config file. I don't have any ikemengo game not set up but let me some days and I will show you how to do it.

That's very much appreciated. I look forward to your suggestions. The controller setup GUI doesn't seem to work.

**Comment by Kelvfimer** [comment]
@25minutes there is a file called config.json in everygame that normally is in the save folder.  If not look for it.

You have to open it and look for JoystickConfig entry, the first entry indexed 0 is the player one you and they will have some sets of keys matched with numbers.

In paralell open a putty terminal to Emuelec and run sdljoytest.

Press the different pad keys, in the terminal will appear an entry and a number, with thatt write it down to the proper key in the file. 

In my case I use a Xbox360 pad and mine are 

  "JoystickConfig": [
    {
      "Joystick": 0,
      "Buttons": [
        "11",
        "12",
        "13",
        "14",
        "0",
        "1",
        "5",
        "2",
        "3",
        "-12",
        "7",
        "4",
        "-10",
        "6"
      ]
    },

**Comment by 25minutes** [comment]
> @25minutes there is a file called config.json in everygame that normally is in the save folder. If not look for it.
> 
> You have to open it and look for JoystickConfig entry, the first entry indexed 0 is the player one you and they will have some sets of keys matched with numbers.
> 
> In paralell open a putty terminal to Emuelec and run sdljoytest.
> 
> Press the different pad keys, in the terminal will appear an entry and a number, with thatt write it down to the proper key in the file.
> 
> In my case I use a Xbox360 pad and mine are
> 
> "JoystickConfig": [ { "Joystick": 0, "Buttons": [ "11", "12", "13", "14", "0", "1", "5", "2", "3", "-12", "7", "4", "-10", "6" ] },

Thank you very much! It works properly now.

**Pull request merged**
