### PR TITLE
[OGA]: RTL8812AU module and sleep mode 

### PR DESCRIPTION
**Pull request by KiwiHop**
For Odroid Go Advance,
Added the RTL8812AU module from aircrack-ng. this module compiles and works (tested with TP link archer Nano) for the OGA.
Added Sleep support while keeping the current hotkeys mapping:

F1 + Up -> Volume up
F1 + Down-> Volume down
F1 + Left-> Brightness up
F1 + Right-> Brightness down
F1 + R -> Toggle Headphones
F1 + Power Key -> Shutdown
Power Key -> Sleep

Fixes USB dead and audio at max after resume. There's a tiny fraction of time where the audio is set to max after resume, before the state set is performed, I cannot get rid of.

### CODE REVIEW

**Comment by shantigilbert** [comment]
Thank you!

**Comment by circruiz** [comment]
> For Odroid Go Advance,
> Added the RTL8812AU module from aircrack-ng. this module compiles and works (tested with TP link archer Nano) for the OGA.
> Added Sleep support while keeping the current hotkeys mapping:
> 
> F1 + Up -> Volume up
> F1 + Down-> Volume down
> F1 + Left-> Brightness up
> F1 + Right-> Brightness down
> F1 + R -> Toggle Headphones
> F1 + Power Key -> Shutdown
> Power Key -> Sleep
> 
> Fixes USB dead and audio at max after resume. There's a tiny fraction of time where the audio is set to max after resume, before the state set is performed, I cannot get rid of.

I just test 
> F1 + Left-> Brightness up
> F1 + Right-> Brightness down
is not working,now
> F1 + Left-> Save State +
> F1 + Right-> Save State -

**Comment by shantigilbert** [comment]
It was changed to F3, not F1

**Comment by circruiz** [comment]
I have a question.
I just play Arc The Lad II (PS1 Game) at the time I save game (Not save state),Game was quit to main menu ,So cannot save game right? or I did something wrong?
Thank you so much

**Pull request merged**
