### PR TITLE
EE - hypseus gamepad config fix

### PR DESCRIPTION
**Pull request by Langerz82**
For Hypseus, all gamepads should still work without an issue.

Needs testing.

### CODE REVIEW

**Comment by Langerz82** [comment]
I tested this a bit, controls seem to be working but I have to test more.

**Comment by Langerz82** [comment]
commit.

**Comment by shantigilbert** [comment]
Please fix the conflicts

**Comment by Langerz82** [comment]
hold up on this patch I haven't made it so a default ini file is copied across.

**Comment by Langerz82** [comment]
ok to commit.

**Pull request merged**
