### PR TITLE
setres new, and change res emulator.

### PR DESCRIPTION
**Pull request by Langerz82**
Sorry about the space fixes. I can't seem to change it in the editor yet

### CODE REVIEW

**Comment by Langerz82** [comment]
ok whitespace fixes removed.

**Comment by shantigilbert** [comment]
Thank you, much better, now I can focus on the real changes.

I will test this and let you know. I am still not keen on how the resolution is set (on the run arguments, instead of emuelec.conf) but I will try it either way.

**Comment by Langerz82** [comment]
It should run the display configs off of emuelec.conf as you suggested, unless my changes were incorrect.

**Comment by shantigilbert** [comment]
Oh, sorry I didn't check the other PR. Ignore my comment :)

**Comment by Langerz82** [comment]
One thing I'm not sure about is when the display should go into the native emulator resolution so the screen doesn't corrupt while switching from emulationstation to the game.

**Comment by shantigilbert** [comment]
I appreciate the changes, can you tell me which device you are testing this in? I have limited time right now and I need to properly test this to make sure it does not break other devices before I merge it.

**Comment by Langerz82** [comment]
I'm testing it on a S922X Beelink GT King Pro. Give me roughly 24 hours from now and I'll properly test it on my device too.

**Comment by Langerz82** [comment]
I'm gonna test it now so give me a couple hours to compile and put on a card.

**Comment by Langerz82** [comment]
I fell asleep as it was late give me an hour tops ill test it now.

**Comment by Langerz82** [comment]
Hey,

DO NOT COMMIT!

It had a bug in the Gamecube gamelist the options arent showing up, not sure why I think it's because it has only one emulator option I gotta check the code.
Also changing the resolution made no difference to launching retroarch, no sure if it actually changed resolutions or not.

**Comment by Langerz82** [comment]
Gotta test the new changes quickly, to make sure it doesn't affect any other options. I'm compiling atm.

**Comment by Langerz82** [comment]
I'm testing again, but it should now work as the emu res wasn't being retrieved properly.

**Comment by Langerz82** [comment]
Ok my latest PR's are confirmed working. I tried opening dolphin and retroarch and both drop res if it's natively changed. I tried ports,n64, and gamecube, they all working good.

Image was: Am-logic generic . Chipset I used was: s922x Beelink kt king pro.

Confirmed to commit.

**Comment by Langerz82** [comment]
Hey, sorry about the delay, I had a few little stupid errors I needed to fix.

**Comment by shantigilbert** [comment]
I found a bug on the profile.d file I will push a commit in a few min, after the commit is pushed to get the settings you should use:
```
get_ee_setting nativevideo "${PLATFORM}" "${ROM}"
```

This will make it so that you can now use:
```
VIDEO_EMU=$(get_ee_setting nativevideo "${PLATFORM}" "${ROM}")
```

and it should work, as any other setting, per game, platform or global (altho in this case global is not used)

**Review by shantigilbert — CHANGES_REQUESTED** [review]
I found a bug on the profile.d file I will push a commit in a few min, after the commit is pushed to get the settings you should use:
```
get_ee_setting nativevideo "${PLATFORM}" "${ROM}"
```

This will make it so that you can now use:
```
VIDEO_EMU=$(get_ee_setting nativevideo "${PLATFORM}" "${ROM}")
```

and it should work, as any other setting, per game, platform or global (altho in this case global is not used) 


EDIT: Tested it. You need to move your code block to after the `$BASEROMNAME` gets populated. so that it looks like this: 

Also, since I am trying to have global scripts and binaries, sourcing the file should look first for the file in `/emuelec/bin`

also note that I have not tested this, and it might need cleaning up/fixing

```
ROMNAME="$1"
BASEROMNAME=${ROMNAME##*/}
GAMEFOLDER="${ROMNAME//${BASEROMNAME}}"

[[ -f "/emuelec/bin/setres.sh" ]] && SET_DISPLAY_SH="/emuelec/bin/setres.sh" || SET_DISPLAY_SH="/usr/bin/setres.sh"
VIDEO=$(get_ee_setting global.videomode)
[[ -z "$VIDEO" ]] && VIDEO=$(get_ee_setting ee_videomode)
VIDEO_EMU=$(get_ee_setting nativevideo "${PLATFORM}" "${BASEROMNAME}")
```

**Comment by shantigilbert** [comment]
Any news on this and the other PR?

**Comment by Langerz82** [comment]
Hey man, I gotta do some other stuff and will include your changes and test it tomorrow so about 24 hours from now.

**Pull request closed without merging**
