### PR TITLE
Dev flycast joy arcade fix

### PR DESCRIPTION
**Pull request by Langerz82**
Allows the FlycastSA emulator to work with Arcade controls when selecting Arcade Games to in FlycastSA. Tested with changes and working.

Only issue is that Flycast needs configurable button mapping like Advmame, but it's quite a bit of work. Not sure it's worth it when people can play Flycast Arcade Games in Retroarch ok.

### CODE REVIEW

**Comment by shantigilbert** [comment]
I am not sure I quite understand what you mean by "Allows the FlycastSA emulator to work with Arcade controls" what does this mean exactly? and what was the issue ?

**Comment by Langerz82** [comment]
Ah, flycastSA uses a different input controller file for arcade emulation such as Naomi, and Atomwave. This makes the input work for them, however the input structure is a bit different. The button mapping is different for each game like fighter games but it's allot of effort to individualize the button mapping for them. For now just the standard mapping should suffice, people can use retroarch flycast libretro if they want custom button mapping. I consider implementing custom button mapping like we did for advancemame a low priority.
Currently the analog controls were not being recognised for ardcade games in flycastSA. This fixes that issue, but yeah as mentioned before the button mapping kinda sucks still lol.

**Comment by shantigilbert** [comment]
If this is still required it needs to be fixed

**Comment by Langerz82** [comment]
Should work fine, commit.

**Pull request merged**
