### PR TITLE
Set Resolution - Fixes

### PR DESCRIPTION
**Pull request by Langerz82**
Set Resolution Fixes.
1. When FBNeo core with Retroarch errors, the current code does not switch the native_video back if it's meant to change. This contains the fix for that.
2. When you change the resolution and restart, the current code does not switch the resolution properly as it's not forced to set. This also contains the fix for that.
3. Minor update to video bordering, should not call if the user does not set it explicitly except for cvbs cases. It should also allow platform specific window bordering, the emuelecRunEmu needs to parse the platform variable. 
4. Fixes to game loading screen, it had some incorrect file paths.

### CODE REVIEW

**Comment by Langerz82** [comment]
All of it looks correct but I have to spend a few days trying different emulators and making sure everything is working ok.

**Comment by shantigilbert** [comment]
Please note that I have removed the `blank_buffer` function (change still uncommitted) , it is causing the return to ES from a game to be REALLY slow, so we need to find another way that does not use `dd` and it's faster

**Comment by Langerz82** [comment]
@shantigilbert 
I've got a much faster method, but I need to test it on EmuELEC as when removing the blanking functions might have adverse effects.
```
#!/bin/sh

blank_buffer()
{
  # Blank the buffer.
  #echo 1 > /sys/class/graphics/fb1/blank
  dd if=/dev/zero of=/dev/fb1 bs=8M conv=async,notrunc > /dev/null 2>&1
  #echo 0 > /sys/class/graphics/fb1/blank
  #echo 1 > /sys/class/graphics/fb0/blank
  dd if=/dev/fb1 of=/dev/fb0 bs=8M conv=async, notrunc > /dev/null 2>&1
  #echo 0 > /sys/class/graphics/fb0/blank
  [[ "$EE_DEVICE" == "Amlogic-ng" ]] && fbfix
}

START=$(date +%s%3N)
blank_buffer
END=$(date +%s%3N)
RESULT=$(( END-START ))
echo "delay: $RESULT"
```
The result for me was 12milliseconds.

**Comment by Langerz82** [comment]
Needs the blank guards to protect the buffer memory space during modification. I'll see if I can make it faster.

**Comment by miwasp** [comment]
In its current state it is not only VERY slow on the OGS, there is also some kind of (memory?-)leak.
After rebooting the device, the first start and stop of any game takes around 12-15 seconds!
After that it gets slower every time you start a game. Starting a game for the 4th time for example lasts 20-25 seconds.
Some time after the 5th start of a game ES crashes.

If i do only one change then and reboot the OGS, starting and stopping lasts around 4 seconds, no matter how often i do it. This one change is removing the four "blank_buffer"-lines in emuelecRunEmu.sh.

**Comment by Langerz82** [comment]
The blank_buffer code section serves a function in clearing pixel artifices when making transitions, so just removing it makes the screen transitions ugly. It could of been the high dd blocksizes that was maybe causing the slowdowns.
I will look into the memory usage a bit more to see where there may be a memory leak, but with this dev release I have been unable to replicate your issue.
Maybe the game launch processes are not killing off properly? Miwasp what EmuELEC version are you using? Built from latest dev?

**Comment by Langerz82** [comment]
The blank buffer should only be taking about 100ms at most, I couldn't shave off more time on it.
I noticed force_kill was being called asynchronously which may have affected the memory cleanup.
I have updated the code in this PR and needs to be tested.

@miwasp If you could SSH into your EmuELEC and type in top then when showing all the processes press d and make the time refresh 0.5 secs. Then run the games as you would, closing them too, and observe what the processes are doing it might help us isolate your issue.

**Comment by miwasp** [comment]
I built from latest dev. I created two test files like yours from above. This is copied from the current dev:
```
#!/bin/sh

blank_buffer()
{
  # Blank the buffer.
  echo 1 > /sys/class/graphics/fb1/blank
  dd if=/dev/zero of=/dev/fb1 bs=8M > /dev/null 2>&1
  echo 0 > /sys/class/graphics/fb1/blank
  echo 1 > /sys/class/graphics/fb0/blank
  dd if=/dev/zero of=/dev/fb0 bs=32M > /dev/null 2>&1
  echo 0 > /sys/class/graphics/fb0/blank
  [[ "$EE_DEVICE" == "Amlogic-ng" ]] && fbfix
}

START=$(date +%s%3N)
blank_buffer
END=$(date +%s%3N)
RESULT=$(( END-START ))
echo "delay: $RESULT"
```
and this is the output:
```
OGS:~/xxx # ./testbufold.sh
./testbufold.sh: line 6: /sys/class/graphics/fb1/blank: No such file or directory
./testbufold.sh: line 8: /sys/class/graphics/fb1/blank: No such file or directory
delay: 1203
OGS:~/xxx # ./testbufold.sh
./testbufold.sh: line 6: /sys/class/graphics/fb1/blank: No such file or directory
./testbufold.sh: line 8: /sys/class/graphics/fb1/blank: No such file or directory
delay: 1208
OGS:~/xxx # ./testbufold.sh
./testbufold.sh: line 6: /sys/class/graphics/fb1/blank: No such file or directory
./testbufold.sh: line 8: /sys/class/graphics/fb1/blank: No such file or directory
delay: 1246
```
This is copied from this PR (your latest changes):
```
#!/bin/sh

blank_buffer()
{
  # Blank the buffer.
  echo 1 > /sys/class/graphics/fb1/blank
  dd if=/dev/zero of=/dev/fb1 bs=1M conv=async,notrunc > /dev/null 2>&1
  echo 1 > /sys/class/graphics/fb0/blank
  dd if=/dev/zero of=/dev/fb0 bs=1M conv=async, notrunc > /dev/null 2>&1
  echo 0 > /sys/class/graphics/fb0/blank
  echo 0 > /sys/class/graphics/fb1/blank
  [[ "$EE_DEVICE" == "Amlogic-ng" ]] && fbfix
}

START=$(date +%s%3N)
blank_buffer
END=$(date +%s%3N)
RESULT=$(( END-START ))
echo "delay: $RESULT"
```
This is the output:
```
OGS:~/xxx # ./testbufnew.sh
./testbufnew.sh: line 18: /sys/class/graphics/fb1/blank: No such file or directory
./testbufnew.sh: line 23: /sys/class/graphics/fb1/blank: No such file or directory
delay: 59
OGS:~/xxx # ./testbufnew.sh
./testbufnew.sh: line 18: /sys/class/graphics/fb1/blank: No such file or directory
./testbufnew.sh: line 23: /sys/class/graphics/fb1/blank: No such file or directory
delay: 58
OGS:~/xxx # ./testbufnew.sh
./testbufnew.sh: line 18: /sys/class/graphics/fb1/blank: No such file or directory
./testbufnew.sh: line 23: /sys/class/graphics/fb1/blank: No such file or directory
delay: 57
```
So this is much better. I'm currently testing, if i can find more information about the potential leak...

**Comment by Langerz82** [comment]
@miwasp Ah excellent diagnostic info, let me know how the new code performs. ^^

**Comment by miwasp** [comment]
It's definitely NOT a memory leak. I stopped looking into it any further as your new code works fine.
With the new code i cannot reproduce the old behavior up to crashing ES and its only minimal slower than without "blank_buffer".

**Comment by shantigilbert** [comment]
Also just FYI, check_hard_kill has also been deleted, this should be handled by gptokeyb, which I already updated with the functionality that was removed.

**Comment by shantigilbert** [comment]
Why not add `if [ -e "/sys/class/graphics/fb1/blank" ]` ? it makes to sense to do all of that call if the path does not exists, which is the case for hand-helds, in fact, is this call even needed at all on handhelds? 
Maybe a `if [[ "${EE_DEVICE}" != "OdroidGoAdvance" ]] && [[ "${$EE_DEVICE}" != "GameForce" ]]; then` should be at the beginning of the call? that way it is skipped altogether if its not needed. 

> OGS:~/xxx # ./testbufnew.sh
> ./testbufnew.sh: line 18: /sys/class/graphics/fb1/blank: No such file or directory
> ./testbufnew.sh: line 23: /sys/class/graphics/fb1/blank: No such file or directory
> delay: 59
> OGS:~/xxx # ./testbufnew.sh
> ./testbufnew.sh: line 18: /sys/class/graphics/fb1/blank: No such file or directory
> ./testbufnew.sh: line 23: /sys/class/graphics/fb1/blank: No such file or directory
> delay: 58
> OGS:~/xxx # ./testbufnew.sh
> ./testbufnew.sh: line 18: /sys/class/graphics/fb1/blank: No such file or directory
> ./testbufnew.sh: line 23: /sys/class/graphics/fb1/blank: No such file or directory
> delay: 57

**Comment by Langerz82** [comment]
I don't think the blanking of fb1 is even needed so I removed it, and also check_hard_kill. Needs to be tested properly but it seems to be working much better on my end.

**Comment by shantigilbert** [comment]
Hard kill is handled by gptokeyb, there is no need to have it. It was giving me a lot of issues with ports, and gptokeyb should be the one handling this anyways

**Comment by shantigilbert** [comment]
@Langerz82 couls you separate the changes to separate pr? Recently we had the issue with all the changes that were made on one PR and it was a nightmare finding the issue

**Comment by Langerz82** [comment]
Good to commit, I've tested with a few emulators. As long as the emulator running has a kill command all should run fine.

**Comment by Langerz82** [comment]
I have to test it one more time make sure it's ok.

**Comment by Langerz82** [comment]
Good to go! :dancers:

**Comment by shantigilbert** [comment]
Thanks

**Pull request merged**
