### PR TITLE
Fixing "genesis genh" typo

### PR DESCRIPTION
**Pull request by AchillesPDX**
Fixing typo for the megadrive platform. Fixes achievements for Genesis and Genesis Hacks

### CODE REVIEW

**Comment by AchillesPDX** [comment]
Not fixed. Don't know why

**Comment by AchillesPDX** [comment]
Doesn't fix retroachievements, but it's still a typo, so I'm reopening.

**Comment by shantigilbert** [comment]
You need to rebase your repo before opening the PR (to avoid unnecessary commits)

**Comment by AchillesPDX** [comment]
Ignore this one and delete if possible

**Pull request closed without merging**
