### PR TITLE
EE - joy common - controller - order fix and revision

### PR DESCRIPTION
**Pull request by Langerz82**
This is an attempt at fixing the order of the controller for some standalone applications.

Issue was originally found here:
https://emuelec.discourse.group/t/controller-profile-issue-with-standalone-cores-4-5/1177/14

There is also some fixes and improvements to the joy common functions.

### CODE REVIEW

**Comment by Langerz82** [comment]
Also added fix for:
https://github.com/EmuELEC/EmuELEC/issues/932

The keyboard/mouse device was being picked up as a game controller. Now all devices found will need to be found in the SDL gamecontrollerdb.txt to be recognised as a valid game controller device.

**Comment by Langerz82** [comment]
Should default to normal sort ordering, If EE_JOY_ORDER_NEW file in ~/.config then check more complex method.

```
  JOYS=$(ls -A1 /dev/input/js* | sort )
  if [[ -f "/storage/.config/EE_JOY_ORDER_NEW" ]]; then
    JOYS=$(cat /tmp/input_devices | grep -A2 "S: Sysfs=" \
      | awk '/^S:/ {s=$0} /^H:/ {print s "\t" $0}' | sort -t $'\t' -k2 \
      | sed 's,.*\(.\{4\}\)$,\1,' | sed 's/ //g')
  fi
```

**Comment by Langerz82** [comment]
ready to commit.

**Comment by Langerz82** [comment]
Had to change the obtaining of the joys variable to remove the previous directories and "\".

**Comment by Langerz82** [comment]
@shantigilbert 
I'm thinking that I should add to this change to allow changes to the controller order based on the values "--controller" sends to emuelecRunEmu.sh, what do you think?

**Comment by Langerz82** [comment]
@shantigilbert 
I tested this properly with swapping devices around and trying to make it preserve order which it does. In EmulationStation setting the controller order will not override it. There should be no need too anyway if ordering is properly preserved. If there are rare complaints I can make it so the ES ordering will override the automatic configs.

**Comment by Langerz82** [comment]
@shantigilbert hold up I'm going to incorporate the ES controller config overrrides into joy_common.

**Comment by Langerz82** [comment]
I am testing this with different devices and ordering changes. Hope it works fine, I checked line by line to debug.

**Comment by Langerz82** [comment]
There is still one bug in this I should solve. If the user partially forces just one or two controllers it makes it player 1. I'll fix it tomorrow for now I need sleep haha.

**Comment by shantigilbert** [comment]
> @shantigilbert I'm thinking that I should add to this change to allow changes to the controller order based on the values "--controller" sends to emuelecRunEmu.sh, what do you think?

I think that is a great idea

**Comment by Langerz82** [comment]
Ok man, It should be ready for testing. I will test it here. I ran a few quick tests with dummy data and works so far.

**Comment by Langerz82** [comment]
this needs a couple more tests with various emulators. will test more tomorrow.

**Comment by Langerz82** [comment]
Tested on different controller and fiddled with the controller ordering to see if it would respect the ES Controller order overrides and it works good. Also tested on different emulators. People can still just use legacy ordering if they wish (what we currently use). You can commit this it's good to go!

**Pull request merged**
