### PR TITLE
Ee Arm Build Image.

### PR DESCRIPTION
**Pull request by Langerz82**
EE Arm Build changes as mentioned in another PR. To add 32-bit packages to your build simply use variable ADD_ARM followed by the packages to add and "make  image_with_arm". For example:

```
PROJECT=Rockchip DEVICE=RK3399 ADD_ARM="retrorun retroarch" ARCH=aarch64 DISTRO=EmuELEC make image_with_arm
```

ref:
https://github.com/EmuELEC/EmuELEC/pull/907

### CODE REVIEW

**Comment by shantigilbert** [comment]
I am sorry but I do not like this script... it assumes many things that are not there. 

1.- You call to compile a 32bit and a 64bit package, that package will be overwritten by either one, but there will not be 2
2.- If any of those binaries needs a library, where will they be copied from? and where does this happen? for example in the case of Retroarch that needs a ton of libraries, all of these will be missing, unless you modify each package to do this. 
3.- it adds a lot of compilation time to the image (2 toolchains + 2 packages for each added) and the resulting image will not work for reasons stated on N.-3 

It will be easier if you want to create a 32bit app for testing to just add `ARCH=arm` to the `make image` command.

**Comment by Langerz82** [comment]
Unfortunately I do not know a better way, as I adopted the change from AmberELEC. If there is an easier and cleaner way of being able to create 32-bit packages I'd love to use the solution.

**Comment by shantigilbert** [comment]
> edit: You are probably right maybe I can do an ARCH=arm make image then just copy the binaries across, what about 32-bit
> dependencies though?

That is the main problem, you also need to copy those... but that is why the `emuelec-32bit-libs` package exists, which gets the files from https://github.com/EmuELEC/emuelec-32bit-libs

I created a script that does this automatically for me, but its a mess.

**Comment by Langerz82** [comment]
Might as well close this, as it's not needed really, and will still be able to be searched if someone needs it for whatever.

**Pull request closed without merging**
