### PR TITLE
Dev fix setres start

### PR DESCRIPTION
**Pull request by Langerz82**
This fixes the resolution change at the start, as well as adding slight delay for buffer to reset properly.

### CODE REVIEW

**Comment by Langerz82** [comment]
Hold up the sleep at the end causes display corruption. Let me test further before adding this.

**Comment by Langerz82** [comment]
Ok, I gotta test it more on a variety of configs, and do one test on a clean install.

**Comment by Langerz82** [comment]
During a fresh boot the start video shows blank and im getting buffer corruption, I'll take a proper look at it tomorrow (it 1am here).

**Comment by Langerz82** [comment]
@shantigilbert Hey where is the line that launches the video on a fresh install?

**Comment by shantigilbert** [comment]
> 
> @shantigilbert Hey where is the line that launches the video on a fresh install?

you mean the intro video? 

https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/emuelec/bin/show_splash.sh#L135

**Comment by Langerz82** [comment]
Ok, I fixed the boot video to show, and simplified the show splash code a bit. Also setres needed minor changes in the order of commands so it needs a bit more testing, but I'm happy with it so far, no glitches that I've seen yet.

**Comment by shantigilbert** [comment]
Instead of creating `get_config_value.sh` can't this be in the [profile.d](https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/emuelec/profile.d/99-emuelec.conf) this way the function will be loaded and available for all scripts. Or alternatively in [emuelec-utils](https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/emuelec/bin/emuelec-utils) just so we don't have to create yet another file for just one function

**Comment by Langerz82** [comment]
@shantigilbert sure np, also I added a default switch which tries to set the display for less generic video modes.

**Comment by shantigilbert** [comment]
Thanks, as soon as the get_config_value.sh change is made I will merge this.

**Comment by Langerz82** [comment]
I haven't tested this yet, I might later tonight or tomorrow if I get some free time.

Note the new setres boot order:
1. /flash/config.ini hdmimode takes 1st priority.
2. Then the files EE_VIDEO_MODE
3. Last uses the value from emuelec.conf.

**Comment by shantigilbert** [comment]
Thanks

**Pull request merged**
