### PR TITLE
Set res show splash final fix

### PR DESCRIPTION
**Pull request by Langerz82**
Hello,

Ok this is the final fix for for set res and show splash.

1. I have detected a display error when the resolution is 480p for TvTextViewer. I believe it's to do with the program and not these changes.
2. Also advanceMame when exiting out displays brief screen corruption, I think this is also the way advanceMame's process is being killed and not my changes.
3. Also the 480p loading screen is not full screen and is black bordered, we would have to create a separate 480p loading screen as it 16/9 dimensions are 853px in width.
4. The show_splash's are executed as background tasks, so it can keep doing whatever it needs to do.
5. The loading screen does not always appear in cases where the loading is faster or it enters the running program (which then clears the buffer).
6. Tested on both pre-existing installs with the images copied over, and fresh installs (I made sure boot video was working properly on new install and if option selected in ES).
7. Startup tasks text does not show over the loading background like it use too. Not sure if this was deliberate by design or not.

### CODE REVIEW

**Comment by Langerz82** [comment]
I dunno, why it's showing all these commits as I applied a patch off a clean branch. Maybe I should of purged my fork too and reset everything. -.-

**Comment by Langerz82** [comment]
Sorry my attempts at squashing the commit log failed and I do not want to screw around with it too much.

**Comment by Langerz82** [comment]
@shantigilbert 
do not merge yet. I got one more change I want to add.

**Comment by Langerz82** [comment]
**I have detected a display error when the resolution is 480p for TvTextViewer. I believe it's to do with the program and not these changes.**

Regarding issue 1. If the setres for 480p width is set to 854px (the widescreen standard) it displays fine. However the N64 emulators don't recognize 854x480 as a valid resolution and it generates an error. So I guess TvTextViewer would display fine if it can render 720x480.

Anyway, I'm happy with these changes, whenever you are ready to commit.

**Comment by shantigilbert** [comment]
I see you are using ` &` on all the setres and show_splass, This is general not a good idea. if ES or Retroarch/game, load BEFORE the intro is finished (say they use a launch video) they will both show at the same time which will break display. So please revert those OR use a launch video that is a few seconds long to properly test. 

I cannot confirm nor test any of the resolution changes, as again I do not have a 1080p so I will take your word on that one. 

> Hello,
> 
> Ok this is the final fix for for set res and show splash.
> 
>     1. I have detected a display error when the resolution is 480p for TvTextViewer. I believe it's to do with the program and not these changes.
> 
>     2. Also advanceMame when exiting out displays brief screen corruption, I think this is also the way advanceMame's process is being killed and not my changes.
> 
>     3. Also the 480p loading screen is not full screen and is black bordered, we would have to create a separate 480p loading screen as it 16/9 dimensions are 853px in width.
> 
>     4. The show_splash's are executed as background tasks, so it can keep doing whatever it needs to do.
> 
>     5. The loading screen does not always appear in cases where the loading is faster or it enters the running program (which then clears the buffer).
> 
>     6. Tested on both pre-existing installs with the images copied over, and fresh installs (I made sure boot video was working properly on new install and if option selected in ES).
> 
>     7. Startup tasks text does not show over the loading background like it use too. Not sure if this was deliberate by design or not.

1.- No idea, but I know that the viewer works on smaller screens than that... e.g. OGA and GameForce
2.- That is advancemame, since it uses the frame buffer directly 
3.- Agree, but I have no idea how to do that and detect it, guess this will fall into you to make it.
4.- Explained this earlier, please revert this, or do a proper test with intro videos, etc. 
5.- there is nothing we can do other than delay the start which we do not want, I rather it loads quick and not show a splash than to load slow just because of the splash. 
6.- OK
7.- The text is usually not shown, other than at the first boot or a default reset, OR if there is an error, so we need to make sure that the errors still display.

**Comment by shantigilbert** [comment]
I am not sure which change caused this, but you removed the intro splash, now it just shows a black screen until ES loads

**Comment by Langerz82** [comment]
@shantigilbert 
Did you apply these changes for the boot video? I have tested a few times and boot video should display fine with this patch, previously yeah it does not work all the time.

I'm not sure how to display the errors, the code must of changed because I havent changed anything to do with the output of the console.

**Comment by shantigilbert** [comment]
I'll merge this and fix the last bits on the next commit.

**Comment by shantigilbert** [comment]
I just pushed a change that required a bit of changing on show_splash.sh, can you please check if its working with other resolutions? 

Thanks!

**Comment by Langerz82** [comment]
@shantigilbert Hey man just wanted to say the console text overlays the background, I ran a compile just before.

**Comment by shantigilbert** [comment]
Which console text?

**Comment by Langerz82** [comment]
The free software notification at the start.

**Comment by shantigilbert** [comment]
That is how it's supposed to be.

**Comment by Langerz82** [comment]
Yep no worries, I've also simplified the code a bit. Give me a bit of time to test make sure it's ok.

**Pull request merged**
