### PR TITLE
[Bug Fix] Fix EE Audio Volume Adjustment on reset.

### PR DESCRIPTION
**Pull request by Langerz82**
[Bug Fix] Fix EE Audio Volume Adjustment on reset.

### CODE REVIEW

**Comment by junm6802030** [comment]
Hello, I can test the patch now. How do I use the patch file?

**Comment by Langerz82** [comment]
@junm6802030 
Clone the latest Emuelec Project with:
```
git clone https://github.com/EmuELEC/EmuELEC.git
cd Emuelec
git fetch origin pull/1266/head:PR1266
git switch PR1266
```
Build the project locally.

**Comment by junm6802030** [comment]
Want to redo the EE system? I thought just replacing the files would be enough, but this is too complicated and I don’t know how to do it.

**Comment by Langerz82** [comment]
commit.

**Pull request merged**
