### PR TITLE
Fix sdl controllersupport flycastsa

### PR DESCRIPTION
**Pull request by Langerz82**
These are the changes to flycastsa. Also notice I've put a symlink in for /usr/bin gamecontrollerdb. That is so updates to the file from EmuElec will also change any packages that use the old link.

### CODE REVIEW

**Comment by Langerz82** [comment]
Any changes I make from now on I will use a clean clone. That is what is causing the unneeded commit entries.

**Comment by shantigilbert** [comment]
please remove the SDL_GameControllerDB/package.mk changes, they are not needed. 

```
ln -sf /storage/.config/SDL-GameControllerDB/gamecontrollerdb.txt $INSTALL/usr/config/SDL-GameControllerDB/gamecontrollerdb.txt
```
This makes no sense, the file at `$INSTALL/usr/config/SDL-GameControllerDB/gamecontrollerdb.txt` gets copied to `/storage/.config/SDL-GameControllerDB/gamecontrollerdb.txt` on boot if the file does not already exists.

Either I am missing something or this is just creating a link to a file that should already be there in the first place. 

> Any changes I make from now on I will use a clean clone. That is what is causing the unneeded commit entries.

And please do, all the PR's should be done from a clean clone.

**Review by shantigilbert — CHANGES_REQUESTED** [review]
Remove all the changes to packages/sx05re/tools/sysutils/SDL_GameControllerDB/package.mk

**Comment by Langerz82** [comment]
Even the symbolic link? Other stand-alone emulators may end up using the gamecontrollerdb.txt from /usr/bin. If it does no changes can be made to that file because it's read only, and it may be an issue for controllers not added by default.
What if it copies to /usr/bin/gamecontrollerdb.txt.bak and we keep the symbolic link?

**Comment by shantigilbert** [comment]
> /usr/bin

First... your PR does not create anything in /usr/bin if there is a need for the file on usr/bin then it can be added, but that is very different from your PR.

so if that is needed please remove all the changes and just add

```
mkdir -p $INSTALL/usr/bin

ln -sf /storage/.config/SDL-GameControllerDB/gamecontrollerdb.txt $INSTALL/usr/bin
```

Second, not sure if that file is needed in usr/bin, but if it does, the symlink is the right way to add it. 

Your current PR just overwrites the file with a symlink which seems to me it will be a broken symlink.

At least I am not understanding the PR correctly.

**Comment by Langerz82** [comment]
Still need to test it.

**Comment by Langerz82** [comment]
What I was trying to do was have the gamecontrollerdb.txt file still in /usr/config/SDL-GameControllerDB but it's actual contents in /storage/.config/SDL-GameControllerDB/gamecontrollerdb.txt.
So that way if the file gets updated and another standalone program uses the gamecontrollerdb.txt in /usr/config then it would have the updated contents of the new controller configuration.
Maybe there is no easy way to do what I'm thinking. I dont think it's needed in /usr/bin, what is the usual default directory gamecontrollerdb.txt is searched for in most of the time?

**Comment by shantigilbert** [comment]
> 
> 
> Hey @shantigilbert ,
> 
> What I was trying to do was have the gamecontrollerdb.txt file still in /usr/config/SDL-GameControllerDB but it's actual contents in /storage/.config/SDL-GameControllerDB/gamecontrollerdb.txt.
> So that way if the file gets updated and another standalone program uses the gamecontrollerdb.txt in /usr/config then it would have the updated contents of the new controller configuration.
> Maybe there is no easy way to do what I'm thinking. I dont think it's needed in /usr/bin, what is the usual default directory gamecontrollerdb.txt is searched for in most of the time?

You are confusing how things work, `/usr/config/SDL-GameControllerDB/gamecontrollerdb.txt` gets copied to `/storage/.config/SDL-GameControllerDB/gamecontrollerdb.txt` on each boot, if the file does not exist there is no need for a symlink, 

In other words `/usr/config/` gets copied to `/storage/.config`  on each boot, IF the files do not exists. So try it, delete the file `/storage/.config/SDL-GameControllerDB/gamecontrollerdb.txt` or the whole folder, then reboot the device, and the file will have appeared again. 

What you are doing is just creating a symlink to the same file that already exists on the same folder, but overwriting it with a symlink, which in turn breaks the whole thing.  (but I have not tested it) 

There are no changes needed to that package.mk because what you want to do it the default behavior already.

**Comment by Langerz82** [comment]
Ok man, ill revert the changes since they are not relevant to the PR anyway. I was aware emuele.conf has the environment variable defined but the prob is diff apps don't use that shell variable. Is there some kind of standard placement for the gamecontrollerdb.txt to exist in?

**Comment by shantigilbert** [comment]
> Ok man, ill revert the changes since they are not relevant to the PR anyway. I was aware emuele.conf has the environment variable defined but the prob is diff apps don't use that shell variable. Is there some kind of standard placement for the gamecontrollerdb.txt to exist in?

That is up to the app/game, That is the standard SDL_HINT and that ENV variable is what it defines where the file should be, if the app/game does not use it, that is another story that has to be dealt with app by app.

**Review by shantigilbert — APPROVED** [review]

**Comment by Langerz82** [comment]
ok, let me do a quick clean build test on the patch changes, make sure it's working before merge.

**Comment by Langerz82** [comment]
confirmed, working.

**Pull request merged**
