### PR TITLE
Quick fix for savestates

### PR DESCRIPTION
**Pull request by miwasp**

### CODE REVIEW

**Comment by bitnykk** [comment]
This seems fully fixed : all the 4.6 savestates i had that were broken under 4.7 now seems to work fine again in 4.8.

**Comment by alexchobi8n** [comment]
Can somebody explain this to me , i was playing mk unleased and saved everything Good and when i went back to play its stuck on the loading screen ,,, i jave a xf40 v game console. Xinfan

**Comment by worstcase-scenario** [comment]
Your device is not supported as you are probaly are using an illegaly sold and modified version of EmuELEC.

**Comment by alexchobi8n** [comment]
I dont understand i purchased it from amazon eravortx is the store xf40 v game console manufactured by xinfan , what makes it illegaly sold , if you can let me know that be great because i paid 70 for this and i can get my money back and buy a legal one then

**Comment by worstcase-scenario** [comment]
Read this: https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices#about-cheap-devices
https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices#special-note

**Pull request merged**
