### PR TITLE
Dev s905w fixed res

### PR DESCRIPTION
**Pull request by Langerz82**
Hard sets the resolution for Amlogic devices, so no corruption occurs.

### CODE REVIEW

**Comment by shantigilbert** [comment]
I don't think this is the solution, the idea is that if 720p works via config.ini we should use that instead.

**Comment by Langerz82** [comment]
Config.ini can have any vout mode and it just becomes 4K.

**Comment by Langerz82** [comment]
I'll test it a bit more, as I'm not sure what the frame buffers initial value is on a clean image. But I made it 1080p because that's what the frame buffer seems to default too. If it's 4K ES might display ok, but not too sure about games as they use the frame buffer to set resolutions from my understanding.

**Comment by Langerz82** [comment]
Yeah I was right the frame buffer will always default to 1080p. Even if you change the vout mode in config.ini it becomes 4K with a frame buffer thats for 1080p (bad). I tried running retroarch with 4K mode on with a 1080p buffer the game resolution itself was ok but the splashes were corrupted. I think it's better we force 1080p mode as that way it will always match the forced default buffer of 1920x1080p. 

Off note - AdvanceMame doesnt work in 4K mode, we are missing the modeline.

**Comment by shantigilbert** [comment]
You are assuming everyone has a 4k TV or even a 1080p TV, locking a single resolution is not a solution, sorry if no other solution, I rather it not be locked at all.

**Comment by Langerz82** [comment]
If someone doesnt have a HD TV or higher it wouldnt display anyway man. It already locks the frame buffer to 1920x1080 cant change it. It's just if you match the mode to make it work ok or not at all.

**Comment by shantigilbert** [comment]
> You do realise the force 1080p is only for legacy devices "Amlogic" not "Amlogic-ng" right?

Yes. I still don't think its a good idea. I will check it out later and I will let you know. I just ave to take my old s905x device from the box.

**Comment by Langerz82** [comment]
I dont even really see the point in using a latest 64-bit builds for lower spec chips, and the emulators performances has not improved really but each to there own I guess lol.

**Comment by Langerz82** [comment]
This makes resolutions other than 1080p work. However there is a flaw. Because the virtual buffer is set to 1080p when doing resolutions like 1024x768 for example, the aspect ratio is not preserved when being full screen.

**Comment by Langerz82** [comment]
Also this introduces more bugs when you try to launch a game in any other resolution other than 1080p. It crops the game output and it appears off-screen.
Really we need a proper fix in CoreElec-20. I am not sure 19.5 has the same problem.

**Comment by Langerz82** [comment]
Lets close this as it's not a proper solution and has flaws. If someone wants 720p modes and below to work natively they will need to download EmuELEC 4.3.

**Pull request closed without merging**
