### PR TITLE
[URGENT][FIX] Dev fix setres start

### PR DESCRIPTION
**Pull request by Langerz82**
This should fix autostart as it had a syntax error which showed up during testing.

Also the latest Dev build, the video splash was not playing audio and once booted into ES it was picking my controllers when plugged in, but not wirelessly which it use to do fine. I think there may be an issue with SDL somewhere, which would explain the input and audio not working properly.

### CODE REVIEW

**Comment by miwasp** [comment]
Did you read my comment on your last commit?
There is a missing blank in your changes of /etc/profile.d/99-emuelec. You can see errors if you login via ssh. With this missing blank the script cancels and results in an incomplete environment. Maybe your problems have the same root cause.

**Comment by Langerz82** [comment]
Ah, sorry I did not see your comment.
the offending line was this correct?
```
[[ ! -s "$CFG_FILE"< here was missing a space>]] && return
```
Thanks for the spot.

**Comment by Langerz82** [comment]
lol 1 space breaking a whole lotta shit haha. I've recompiled and tested on my device. 

@shantigilbert  URGENT - Please read, Please commit this asap as it's currently breaking a whole lotta shit!

**Comment by Langerz82** [comment]
@shantigilbert thanks and apologies for the typo. I made a late change at the last minute to check for the existence of the file and did not test properly. In future I will test more rigorously and make sure my changes are stable before a commit.

**Pull request merged**
