### PR TITLE
[Feature] Cloud Loading and Saving for retroarch auto saves and state saves.

### PR DESCRIPTION
**Pull request by Langerz82**
This change enables the user to cloud load and save for retroarch (with rclone and google drive, dropbox or some other one). This feature needs a emuelec.conf variable added to work.

The emuelecRunEmu sends updated state and save files whenever it's closed. This is a bit of a slow process so I'm considering removing it from the file. Takes around 10 seconds or so.

With an EmulationStation code change I've enabled the option for a selected game to backup the save/state files on the cloud or to retrieve them. It's in the game options menu, the required PR change is on it's way (I have to test it again).

### CODE REVIEW

**Comment by shantigilbert** [comment]
I appreciate all the PR's but can we try and complete them? we have 6 right now all in draft and I am not sure how to proceed with all of those, please let me know.

**Comment by Langerz82** [comment]
I say commit this, it can be tested more in the dev version. It has a flag that can disable it anyway, if it has a bug which it shouldn't. I have tested this quite thoroughly.

**Comment by Langerz82** [comment]
Hold on the commit, I'm going to make a few small changes to this.

**Comment by Langerz82** [comment]
To work with EmulationStation see here:
https://github.com/EmuELEC/emuelec-emulationstation/pull/66

**Comment by Langerz82** [comment]
I have tested this, it can be committed with ES PR https://github.com/EmuELEC/emuelec-emulationstation/pull/66 . :dancers:

**Review by shantigilbert — APPROVED** [review]

**Comment by LeoWalk77** [comment]
> Essa alteração permite que o usuário armazene em nuvem o carregamento e salve para retroarch ( com rclone e unidade do Google, dropbox ou outro ). Esse recurso precisa de uma variável emuelec.conf adicionada ao trabalho.
> 
> O emuelecRunEmu envia um estado atualizado e salva arquivos sempre que é fechado. Esse é um processo lento, então estou pensando em removê-lo do arquivo. Demora cerca de 10 segundos ou mais.
> 
> Com uma alteração no código EmulationStation, ativei a opção de um jogo selecionado para fazer backup dos arquivos de salvar / declarar na nuvem ou recuperá-los. Está no menu de opções do jogo, a alteração de PR necessária está a caminho ( Eu tenho que testá-lo novamente ).

Good Morning!!! Could you create a video tutorial on Youtube on how to activate this feature in version 4.6? I already have Rclone enabled on my EmuELEC since version 4.5 and I would really like to add this feature here on my recently updated EmuELEC 4.6. I appreciate your attention in advance.

**Comment by Langerz82** [comment]
@LeoWalk77 for Retroarch for cloud saves.

**Step 1.** 
Setup rclone to be configured with a remote drive called "emuelec" by running in SSH: "rclone config", and setup a new drive. 
In /storage/.config/rclone/rclone.conf should look like this:
```
[emuelec]
type = drive
client_id = SOME_CLIENT_ID
client_secret = SOME_SECRET
scope = drive
token = {"access_token":" SOME_ACCESS_TOKEN
team_drive =
auth_owner_only = true
```

**Step 2.**
Modify the es_systems.cfg, by adding cloudsave into emulator libretro features record like so:
```
<emulator name="libretro" features="ratio, smooth, shaders, pixel_perfect, decoration, latency_reduction, game_translation, nativevideo, cloudsave">
```

**Step 3.**
Then in EmulationStation get into the platform gamelist you want to keep saves, and press SELECT, Advanced Game Options and put on Enable Cloud Saves.

**Pull request merged**
