### PR TITLE
Display-Resolutions changes for each Emulator.

### PR DESCRIPTION
**Pull request by Langerz82**
Display-Resolutions changes for each Emulator.

Note - Hopefully I've done this right as I ran into a few issues.

### CODE REVIEW

**Comment by shantigilbert** [comment]
Please change the branch from `master` to `dev`

**Comment by shantigilbert** [comment]
Also, we already have a script to modify the resolution, why do we need another one? either merge your changes to the `setres.sh` file or use that one.

**Comment by Langerz82** [comment]
It needs to be tested properly which I will do later today or tomorrow. ^-^

Kind regards,
Josh L.

**Comment by Langerz82** [comment]
fixed setres.sh to be compatible with /bin/sh and not /bin/bash.

**Pull request closed without merging**
