### PR TITLE
Zerotier to emuelec

### PR DESCRIPTION
**Pull request by Diegrosan**
Hello how are you, Please check the commit, I don't have much hope on github, but I want to help.

(https://github.com/EmuELEC/EmuELEC/compare/dev...Diegrosan:EmuELEC:dev)

(https://github.com/EmuELEC/EmuELEC/commit/e98a84f43bff9ee9e9c00de77911c6a469d1efea)

(https://github.com/EmuELEC/EmuELEC/commit/f21553d1ef0fa5678aa07b52d971e47d0787dfcc)

### CODE REVIEW

**Comment by Diegrosan** [comment]
added zerotier-one to the dependency, emuelec.
https://github.com/Diegrosan/EmuELEC/commit/9d02e5886dacc2f615d047b632227432f3ef7d06

**Comment by shantigilbert** [comment]
I am not familiar with Zerotier, can you explain why its needed in EmuELEC?

**Comment by shantigilbert** [comment]
I read about what this is, and I believe it is not needed for EmuELEC, I appreciate the PR but it will not be merged. Sorry

**Comment by Diegrosan** [comment]
Alright, I understand, thanks for responding.

**Pull request closed without merging**
