### PR TITLE
set res revised.

### PR DESCRIPTION
**Pull request by Langerz82**
Set res revised.

Needs testing.

### CODE REVIEW

**Comment by Langerz82** [comment]
Use this PR change. The other one is messy with several commits.

**Comment by Langerz82** [comment]
@shantigilbert Dont merge yet, I have a couple tiny fixes.

**Comment by Langerz82** [comment]
@shantigilbert Think I've finally got a proper fix, give me a day or two and I'll test it thoroughly. You wouldn't believe the amount of times I created images and re-booted my device. XD

**Comment by shantigilbert** [comment]
> You wouldn't believe the amount of times I created images and re-booted my device. XD

Yes I can! I have a pile of dead SD cards :P

**Comment by Langerz82** [comment]
@shantigilbert Haha ok. Alright this is a super clean change, but lets give it a few days and test thoroughly. I noticed a separate issue TvTextViewer doesn't have resolution support for 640x480, and the display corrupts if an error is thrown in that mode.

ALL screen transitions should work and be smooth with no workaround hacks needed, include splashes and video. AdvMame is the only one that when force aborting the display will go a bit corrupt briefly.

**Comment by shantigilbert** [comment]
> TvTextViewer doesn't have resolution support for 640x480

This does not make sense, the GameForce chi is 640x480 and TvTextViewer works fine there (or worked, I have not tested with your changes)... so something else is going on. But either way I am not that worried about 640x480 on TV.

**Comment by Langerz82** [comment]
@shantigilbert hey I've tried a few different res's again, and the only time it showed incorrectly is when I used an unsupported resolution on my HD tv, 576p. I'll keep on trying different res's and make sure it's ok.

**Comment by Langerz82** [comment]
Ok, so I replicated the TvTextViewer bug after quit allot of attempts. The native video is set to 640x480 and when the TvTextViewer corrupted the display mode is actually 1280x720. So I think TvTextViewer was trying to display in 640x480 but it's still in 1280x720 HD output mode.
I think maybe if we set a small sleep after the Res switch this might fix the issue, I'll test it out.

**Comment by Langerz82** [comment]
It was the fbfix ordering, the resolution has to change before the amlogic-ng fbfix is called, so sdl gets the correct resolution when executed, and not the previous display.

**Comment by Langerz82** [comment]
Another bug now, reverting back to the ES resolution it's corrupting. Let me try and fix.

**Comment by Langerz82** [comment]
This needs thorough testing as it removes the fbfix on exit of emulator. This code registers the SDL dimensions before the video change actually occurs, and the video is reverted back before output to log or return to ES. I've tested it a little, but it needs more testing and with different devices (I have only amlogic-ng).

**Comment by shantigilbert** [comment]
Unfortunately fbfix is going to be needed since its a problem with the GPU drivers and not the resolution. the only way to remove it is if we switch to DRM drivers, which I have tried several times, but with no real success (device works and boots with some gfx issues are present).

**Comment by Langerz82** [comment]
No probs man, The fbfixes should be working fine, the 1st one was before the setres, which it should be after. I don't think it affected the emulators, but I moved it to it's proper place just to be sure. They are fine in the code I just wasn't sure initially what they did exactly.

**Comment by shantigilbert** [comment]
is this ok to go?

**Comment by Langerz82** [comment]
I'll give it a proper random test before commit in the next few hours before merging.

**Comment by Langerz82** [comment]
It's got another bug, when the resolution isn't supported it sometimes defaults to it's original resolution and when restoring thinks it's the same so exits. I will find a fix.

**Comment by Langerz82** [comment]
Ok with that optimization removed, I'm confident these changes should work fine. You can merge this whenever, I tried allot if different resolutions and the display is working fine, and as it should.
TvTextViewer is displaying in the same res ES does, which is the best solution, at 480p the text is wrapped and silly.

**Comment by Langerz82** [comment]
Confirmed to merge.

**Comment by shantigilbert** [comment]
Thank you!

**Pull request merged**
