### PR TITLE
advmame joycfg changes

### PR DESCRIPTION
**Pull request by Langerz82**
Allows config changes to joystick buttons for advMame for specific games as defined by the Regex expressions.

### CODE REVIEW

**Comment by shantigilbert** [comment]
Can you elaborate on what this does exactly? how do you define which games? and is the .diff file supposed to be in the PR?

**Comment by Langerz82** [comment]
Ok so. It looks at the filename of the launched game you run in Advmame, if it matches any regular expressions added to the cfg_advmame_joy.sh it can modify the joystick button order based on the result joystick index you specify. This allows you to change button configurations depending on the game.
Mortal Kombat and Street Fighter button configurations are added as an example. When you launch those games the buttons for PS3 Controllers matches that of the console editions. By default the buttons to those games are a bit all over the place.
I would like to see more games added, if the button configuration in the Advmame game input configuration menu is saved it makes it fairly easy to convert over. 

```
# AdvMame Button Order.
#def - [1,14] [2,15] [3,13] [4,16] [5,12] [6,11]
#MK  - [1,16] [2,12] [3,13] [4,15] [5,14] [6,11]
#SF  - [1,16] [2,13] [3,11] [4,15] [5,14] [6,12]
```
Shows the different button order and you can swap the buttons in the array to match the difference in the default order (def).
For example def 1,14 and MK is 5,14 so those buttons need to be swapped to be in proper order.

Hopefully this makes more sense now.

**Comment by Langerz82** [comment]
It could also be achieved by adding a different input mapping in the advmame.rc file, but it wouldnt support REGEX strings, each filename would have to be added.

**Comment by Langerz82** [comment]
It seems I cant get 2-players working with this change, I'll see if it the same without my changes.

**Comment by Langerz82** [comment]
> It seems I cant get 2-players working with this change, I'll see if it the same without my changes.
I had to specify the controllers in emulationstation and change in Controller and Bluetooth settings P1 and P2 controller from "DEFAULT" to "#0 Shanwan PS3 Gamepad" and "#1 Shanwan PS3 Gamepad" respectively, and my changes work fine for both controllers.

I probably should take my code out of the loop, and maybe make the custom button config to be allowed to be enabled or disabled.
What would be the best way to let the user choose if its enabled or disabled do you think?

**Comment by Langerz82** [comment]
Ok so the changes can now be disabled by changing cfg_advmame_joy.sh ADVMAME_JOY_CFG_ENABLE="1" to ADVMAME_JOY_CFG_ENABLE="0".

I could also make this variable retrieved from get_ee_settings if it's more appropriate.

**Comment by shantigilbert** [comment]
That variable, as well as the regex pattern need to be kept on another file that is accessible (/usr/bin is RO) and it needs to be set as off by default, since this does not have a GUI menu, because with no explanation it would be hard for people to figure out why their controllers act differently per game.

**Comment by Langerz82** [comment]
put on hold. I've made a few changes locally and need to test.

**Comment by Langerz82** [comment]
Hey, seems to be working ok, I'll test it more thoroughly over the next few days.

**Comment by shantigilbert** [comment]
There is one thing I noticed (but correct me if I am wrong): 

this is the advancemame/package.mk file

```
mkdir -p $INSTALL/usr/share/advance
if [ "$DEVICE" == "OdroidGoAdvance" ]; then
   cp -r $PKG_DIR/config/advmame.rc_oga $INSTALL/usr/share/advance/advmame.rc
elif [ "$DEVICE" == "GameForce" ]; then
   cp -r $PKG_DIR/config/advmame.rc_gf $INSTALL/usr/share/advance/advmame.rc
else
   cp -r $PKG_DIR/config/advmame.rc $INSTALL/usr/share/advance/advmame.rc
fi
```

as you can see the file `cfg_advmame_joy.sh` never gets copied on build, so this needs to be changed to 

```
mkdir -p $INSTALL/usr/share/advance
if [ "$DEVICE" == "OdroidGoAdvance" ]; then
   cp -r $PKG_DIR/config/advmame.rc_oga $INSTALL/usr/share/advance/advmame.rc
elif [ "$DEVICE" == "GameForce" ]; then
   cp -r $PKG_DIR/config/advmame.rc_gf $INSTALL/usr/share/advance/advmame.rc
else
   cp -r $PKG_DIR/config/advmame.rc $INSTALL/usr/share/advance/advmame.rc
fi

cp -r $PKG_DIR/config/cfg_advmame_joy.sh $INSTALL/usr/share/advance/
```

or something similar

**Comment by Langerz82** [comment]
@shantigilbert 
Good spot. I was missing some code from the PR. I have updated advmame.sh too to reflect the changes from the /usr/share/advance folder.

**Comment by Langerz82** [comment]
@shantigilbert 
Yo man, I'm thinking I might work on a config setting in ES, to assign custom buttons for advmame. Give us some time to work it all out.

**Comment by Langerz82** [comment]
ok, so these changes should support the old way by entering into the cfg_advmame_joy.sh regex patterns for game name wildcards. It also supports retrieving values from the emuelec.conf. The idea is that when I modify ES you will be able to create custom button mappings, then also assign them to a specific game. The new way of doing it will not support wildcard names, a trade off for simplicity I guess.

**Comment by Langerz82** [comment]
I made a few config rename changes for ES to load the values easier and easier retrieval.

**Comment by Langerz82** [comment]
Above should be the last time I edit the changes, I'm pretty happy with the above code and do not foresee any issues with ES being able to handle the config values.

**Comment by shantigilbert** [comment]
Awesome, I will just wait until the ES side is finished and I will merge it. Thanks!

**Comment by Langerz82** [comment]
Ok it's ready for testing with the ES changes.

**Comment by Langerz82** [comment]
@shantigilbert 
Hey ES needs some config values added into the emuelec.conf to work. I have made some checks to disable the feature if there not present. How would I go about adding some lines into emuelec.conf when it detects an upgrade?

**Comment by Langerz82** [comment]
@shantigilbert 
Here is the changes to ES ready for testing:
https://github.com/EmuELEC/emuelec-emulationstation/pull/40

**Comment by Langerz82** [comment]
@shantigilbert 
Did you also add the feature to AdvanceMame in es_features.cfg?
```
<emulator name="AdvanceMame" features="nativevideo,joybtnremap" />
```

**Comment by shantigilbert** [comment]
Well it was in this commit, its a clean install. But yes it is there.

**Comment by Langerz82** [comment]
Have you also switched the mame emulator to AdvanceMame in advanced system options?
Maybe also try adding default="true" in AdvanceMame es_features.cfg.

**Comment by Langerz82** [comment]
@shantigilbert try these settings in emuelec.conf:
```
advmame_joy_remap=1

AdvanceMame.joy_btns=input a button,input b button,input x button,input y button,input r button,input l button,input r2 button,input l2 button

AdvanceMame.joy_btn_indexes=1,2
AdvanceMame.joy_btn_names=mk,sf

AdvanceMame.joy_btn_order0=0 1 2 3 4 5 6 7
AdvanceMame.joy_btn_order1=3 4 2 1 0 5 6 7
AdvanceMame.joy_btn_order2=0 1 2 3 4 5 6 7

mame.joy_btn_cfg=0
mame.core=AdvanceMame
mame.emulator=AdvanceMame
```

**Comment by shantigilbert** [comment]
Those are also there. 

This should work without any other settings if its a clean install, no?

**Comment by Langerz82** [comment]
Yeah I cant think of any other configs that are needed. It does a feature check, and checks for joy_btns, joy_btn_indexes and joy_btn_names that they are not empty.
Your looking in Advanced System Options right? Advanced Game Options will only show the button cfg selector.
Umm the ES package was updated with the latest commit too right?

I cant think of anything else that might be an issue.

**Comment by shantigilbert** [comment]
Maybe your PRs are missing something? or I am missing how this is supposed to work maybe?

**Comment by Langerz82** [comment]
These are the correct config values that should be committed.

emuelec.conf
```
# Enable Advance mame config buttom remapping 1,0 (default 0)
advmame_joy_remap=1

AdvanceMame.joy_btns=input a button,input b button,input x button,input y button,input r button,input l button,input r2 button,input l2 button

AdvanceMame.joy_btn_indexes=1,2
AdvanceMame.joy_btn_names=mk,sf

AdvanceMame.joy_btn_order0=0 1 2 3 4 5 6 7
AdvanceMame.joy_btn_order1=3 4 2 1 0 5 6 7
AdvanceMame.joy_btn_order2=3 2 5 1 0 4 6 7
```

**Comment by Langerz82** [comment]
Sorry I did not update the EE PR with the correct emuelec.conf values and it's using old values.

**Comment by shantigilbert** [comment]
Ok those values now work. But I still do not understand how users can create their own remappings, are they made directly on the configuration files?

**Comment by shantigilbert** [comment]
But it does work. I will commit the changes to the .conf file. Thanks for the PR!

**Comment by Langerz82** [comment]
The user should be able to alter the mappings in ES Advance System Settings, Create Button Remap.
Currently it supports only create and delete, not editing current ones. If there becomes a real need to have an edit option I'll make a future change.

**Comment by shantigilbert** [comment]
Ok I am liking this! 

More questions: 

* Can the create button remap be also added to the game options? seems like that is where it should go, maybe even based it on that game rom name? 
* When I try to select a map to "Delete" it will prompt me if I want to delete the remap (even tho I have not selected any)

**Comment by Langerz82** [comment]
LOL, Ok I'll make some quick changes so the default ones cant be deleted and so create works for games too.

**Comment by shantigilbert** [comment]
Yeah but the delete function does not work correctly right now, when you open it, it shows "NONE" if you try to choose another one to delete, it will prompt you if you want to delete it even tho you haven;t selected another one. The prompt should not appear until you select one.

**Comment by Langerz82** [comment]
Hmm strange, it usually should only appear when the value selected changes from none. I'll look into it.

**Comment by Langerz82** [comment]
Hey and yeah I like this change too. It was quite a headache to get delete working cause apparently in the nested functions removing records was corrupting and crashing ES erasing normally like vec.erase(vec.begin()+index) had to a iterate variable bloody nightmare to debug! lol

**Comment by Langerz82** [comment]
@shantigilbert what input are you using when deleting? I use a game controller and the prompt occurs only if I change the value. Do you want me to make the event occur when you select back instead? the addsavefunc event.

**Comment by shantigilbert** [comment]
> @shantigilbert what input are you using when deleting? I use a game controller and the prompt occurs only if I change the value. Do you want me to make the event occur when you select back instead? the addsavefunc event.

That is because you are opening the selection box, just push left/right and you get the prompt

**Comment by Langerz82** [comment]
ahhh I did not know you could even do that haha. I'll look into a fix.

**Comment by Langerz82** [comment]
@shantigilbert 
I've had trouble detecting if the popupOptions are displaying on the screen or not. I'll try and fix it tomorrow sat night here.

**Comment by shantigilbert** [comment]
There are still small issues happening, besides the delete one if you select the "AUTO" remap in a game, it gets saved to `emuelec.conf` as `game.joy_btn_cfg=3` (or I assume +1 of how many exists, I have 2)  instead of 0

**Pull request merged**
