### PR TITLE
Dev dolphin optimize and fixes

### PR DESCRIPTION
**Pull request by Langerz82**
Dev dolphin optimize and fixes

A couple of default changes to the config file so it should run smoother for devices.

### CODE REVIEW

**Comment by Langerz82** [comment]
I changed this to a draft because a user reported he got an error with some games possibly due to these changes.

**Comment by Kelvfimer** [comment]
@Langerz82 I tested and it worked for me :)

**Comment by D-Mod9110** [comment]
@Langerz82 

Where do I place emuelecRunEmu.she and set_dolphin_joy.sh? Or find them, anyway?

**Comment by Langerz82** [comment]
@D-Mod9110 
You need to SSH in:
https://github.com/EmuELEC/EmuELEC/wiki/How-to-SSH-into-EmuELEC

And easiest way to use the modified emuelecRunEmu.sh copy/paste one line at a time:
```
cd /emuelec/bin
wget https://raw.githubusercontent.com/EmuELEC/EmuELEC/4e49c4137ab02942aae882c9d675aaec847e8452/packages/sx05re/emuelec/bin/emuelecRunEmu.sh
chmod +x /emuelec/bin/emuelecRunEmu.sh
```
You should now have the updated file that will override the default one.

**Comment by Kelvfimer** [comment]
I think this PR should be merged @shantigilbert  @Langerz82  any other update? thx

**Pull request merged**
