### PR TITLE
Dev asound conf

### PR DESCRIPTION
**Pull request by Langerz82**
This small change:

Allows a user to create a file to specify the default device in a seperate file which seds into asound.conf. For example:
echo hw:0,1 > /storage/.config/ASOUND

Will copy the value into asound if the file and data is present so the default sound will go through it instead of just always being hw:0,0 (the usual default for amlogic-ng).

### CODE REVIEW

**Comment by shantigilbert** [comment]
Does this fix something I am not aware of? all these "hidden" settings can't be good in the long run, no?

**Comment by Langerz82** [comment]
A user reported not having audio through the 3.5mm jack even though he had changed the hw device in ES to hw 0,1. Only changing the asound.conf would fix it. So I figured we make it configurable so users can change the hardware id in the file rather than the whole file. I suppose we could of also have made a change in asound.conf.amlogic-ng but just changing 1 value as opposed to changing the whole file seems to be much easier to do both for user and to instruct with.

**Comment by Langerz82** [comment]
Specifically his solution was to change in asound.conf-amlogic-ng from "hw:0,1" to "hw:0", or "hw:0,1", and he was using an Odroid N2+. Another user has a similar issue and I figured there is not enough cases to make a global change, but a few cases that instructing them to just create an ASOUND file with the hw change much easier fix.

**Comment by shantigilbert** [comment]
I am not understanding this, it seems to me that of the setting in ES is failing to do what it's supposed to, then we should fix it there no? https://github.com/EmuELEC/EmuELEC/blob/73c337e14751065f23589fefe923a8b7532c4949/packages/sx05re/emuelec/bin/emuelec-utils#L19

the `asound.conf` file should get created at startup, and it basically just copies the needed `asounf-(platform).conf` to `asound.conf`
if this is not happening then I think we need to also fix it there.  https://github.com/EmuELEC/EmuELEC/blob/73c337e14751065f23589fefe923a8b7532c4949/packages/sx05re/emuelec/bin/emuelec_autostart.sh#L21

I don't think that adding yet another hidden configuration is the solution, especially in the long run, since nobody is writing documentation.

**Comment by Langerz82** [comment]
ok, then 2 fixes will need to occur
1. We will have to add "hw:0" to ES (value 0), so it applies to just the device and not the sub-devices.
2. setauddev will need to modify asound.conf-${EE_DEVICE} as well as asound.conf since on restart the asound.conf is copied over.
3.

**Comment by Langerz82** [comment]
PR not needed.

**Pull request closed without merging**
