### PR TITLE
retroarch/Amlogic-ng: patch mali_fbdev_ctx.c instead of retroarch.c to fix yoffset>0 issue

### PR DESCRIPTION
**Pull request by spleen1981**
Fixing the issue in context driver source file is cleaner and much more maintainable. Also fixed two other minor issues (avoid setterm call when not available in the system and override calculation of refresh rate when pixclock is not available - division by 0 occurs otherwise).

### CODE REVIEW

**Comment by spleen1981** [comment]
I'll send PR also upstream.
Also `packages/sx05re/emuelec/fbfix` package removal should be evaluated if not needed anymore.

**Comment by shantigilbert** [comment]
> I'll send PR also upstream. Also `packages/sx05re/emuelec/fbfix` package removal should be evaluated if not needed anymore.

Thank you, I will apply it and test it ASAP! 

As for fbfix, sadly is still needed, as other standalone emulators use it because otherwise the window does not update (end up with sound but what it seems to be a frozen screen)

**Comment by spleen1981** [comment]
Already merged upstream in retroarch [f43b19d](https://github.com/libretro/RetroArch/commit/f43b19db4fdb0374a7f341b1ec63a2e4608d3daa), when package.mk will point to this commit or later no patch will be needed anymore here.

**Comment by shantigilbert** [comment]
Thank you! I tested it and it seems to work good so far. I will close this PR as it is no longer needed as you said.

**Comment by spleen1981** [comment]
> Thank you! I tested it and it seems to work good so far. I will close this PR as it is no longer needed as you said.

Yes, and current patch is to be removed as well.

**Pull request closed without merging**
