### PR TITLE
EE-ES Multidisc creation support.

### PR DESCRIPTION
**Pull request by Langerz82**
EE function to support the creation of multidisc m3u files in EmulationStation.

For more info see:
https://github.com/EmuELEC/emuelec-emulationstation/pull/56

### CODE REVIEW

**Comment by shantigilbert** [comment]
Why are these PR's opened as drafts? are they not ready yet?

**Comment by Langerz82** [comment]
They are nearly ready, I would like more testing done. It doesn't help that pretty much noone tests PR's and gives feedback lol.

**Comment by shantigilbert** [comment]
> It doesn't help that pretty much noone tests PR's and gives feedback lol.

I know :( welcome to my world!

**Comment by shantigilbert** [comment]
Please mark the prs ready for review then we can fix the issues if anyone else has them.

**Comment by Langerz82** [comment]
You can go ahead and commit this. Note - In ES when you first create a multidisc or you delete a game ES hangs for awhile. It's not a crash, I think ES loads something in the background, because subsequent creation of multidiscs or deleting games is fast and ES reports no errors or anything.

**Comment by shantigilbert** [comment]
> You can go ahead and commit this. Note - In ES when you first create a multidisc or you delete a game ES hangs for awhile. It's not a crash, I think ES loads something in the background, because subsequent creation of multidiscs or deleting games is fast and ES reports no errors or anything.

Do we know what is it that gets started? maybe comparing `ps` ?

**Comment by Langerz82** [comment]
I have no idea I'd have to dig through all the calls and try and locate the issue. Considering it's only the first time I'm guessing it's probably cacheing the playlist or something.

**Pull request merged**
