### PR TITLE
Dev fix res switch 2

### PR DESCRIPTION
**Pull request by Langerz82**
I've noticed screen corruption that screwed the resolution with previous changes, it happened once or twice.
The new fixes to setres and show_splash when blank ensures it's much cleaner.

For some reason it's showing previous changes for 2 files, I thought I already made to the Dev branch, please ignore those changes.

### CODE REVIEW

**Comment by Langerz82** [comment]
Are you able to reject the changes to autostart.sh and 99-emuelec.conf ?

**Comment by Langerz82** [comment]
ok fixed the changes.

**Comment by shantigilbert** [comment]
I am getting a bit hesitant to merge these changes now... you told me that you properly tested this, and it seems there are changes daily. So please, for future PRs, test them properly for a few days, then report back. I cannot personally test them as I do not have another screen that is not 1080p and I don't get any of the issues your PR's fix. 

Thank you!

**Comment by Langerz82** [comment]
Ok, in future I'll make sure I've tested it thoroughly before proposing any changes.

**Comment by shantigilbert** [comment]
> 
> 
> Ok, in future I'll make sure I've tested it thoroughly before proposing any changes.

Thank you!

**Pull request merged**
