### PR TITLE
Hypseus update

### PR DESCRIPTION
**Pull request by Kelvfimer**
This new version of SDL2 makes it working Hypseus, Fixed using AMBERELEC SDL2_Image changes. THX @dhwz

### CODE REVIEW

**Comment by dhwz** [comment]
@Kelvfimer you can remove the connman change it's unrelated to hypseus fix

**Comment by Kelvfimer** [comment]
@dhwz I had a compilation error with conmann having the version Emuelec had that was fixed with yours :) that's why I changed it.

**Comment by shantigilbert** [comment]
> @dhwz I had a compilation error with conmann having the version Emuelec had that was fixed with yours :) that's why I changed it.

In the future it would be better if when opening a PR you only add the changes needed for that particular PR and not mix them.

**Comment by shantigilbert** [comment]
Thank you!

**Pull request merged**
