### PR TITLE
Unify Brightness

### PR DESCRIPTION
**Pull request by shantigilbert**

### CODE REVIEW

**Comment by miwasp** [comment]
I just tested this.

- The lines 488-492 of emuelecRunEmu.sh must be deleted. Otherwise you would restore the value it was before starting RA, any changes in RA would be discarded.
- The line with sed in emuelecRunEmu.sh has to be (blanks before and after "="):
> sed -i "s|screen_brightness = .*|screen_brightness = ${DEFBRIGHT}|g" ${RACONF}

- The GameForce does not have the brightness setting in RA at all?

I bumped RA to 1.9.5 (0785d4aa7280fc2a9e2ddfdb6db79178c8763da0) for these tests. With the above changes it works really well.

**Comment by shantigilbert** [comment]
> I just tested this.
> 
>     * The lines 488-492 of emuelecRunEmu.sh must be deleted. Otherwise you would restore the value it was before starting RA, any changes in RA would be discarded.
> 
>     * The line with sed in emuelecRunEmu.sh has to be (blanks before and after "="):
> 
> 
> > sed -i "s|screen_brightness = .*|screen_brightness = ${DEFBRIGHT}|g" ${RACONF}
> 
>     * The GameForce does not have the brightness setting in RA at all?
> 
> 
> I bumped RA to 1.9.5 (0785d4aa7280fc2a9e2ddfdb6db79178c8763da0) for these tests. With the above changes it works really well.

Did the changes. 

GameForce should have it, but I have not checked.

**Comment by miwasp** [comment]
Just as a reminder: This also has to be done with the 32bit versions if they are bumped.

**Comment by shantigilbert** [comment]
What 32bit version? of what?

**Comment by miwasp** [comment]
Yes, Retroarch

**Pull request merged**
