### PR TITLE
Set res optimized splash simplified

### PR DESCRIPTION
**Pull request by Langerz82**
1. I optimized setres so it can take into account more various resolutions and has less code, It's also been simplified somewhat. You may notice MODE on 720x480 becomes 480p that is a bit of a hack so 720x480 can be displayed on HD TV's.

2. Simplified splash a bit so it's a bit easier to read. It works the same, I've tested it.

In setres I left in the intro conditional as I thought you may have used it.

I've also made emulationstation be able to load nativevideo's supported by the display (seperate PR).

### CODE REVIEW

**Comment by Langerz82** [comment]
oh yeah I also left in your randomization option for boot video.

**Comment by Langerz82** [comment]
hmm, I'm thinking maybe I remove the 720x480 to 480p hack. Maybe it's better people set windowed mode and the resolution in retroarch too 720x480. What do you think?

**Comment by shantigilbert** [comment]
The reason I reverted the video part from show_splash was that is was not working as you described, it worked fine before and I don't see a reason to change the code... But I have not tested this change. 

Also, what does the changes to show_splash.sh has to do with setres.sh? I think these should be 2 separate PR's as again the changes have nothing to do with each other and it makes it a pain to debug later....

I am not going to merge this one until you have properly tested this, this is about the 6th PR about the same issue, and it seems you do not properly test these changes as they come one after the other, there is no rush, take your time and properly test them. 

Also please use a clean clone for PRs otherwise all of your commits get submitted to this PR, its not a problem for me, but it is good practice in general for PRs

**Comment by shantigilbert** [comment]
> hmm, I'm thinking maybe I remove the 720x480 to 480p hack. Maybe it's better people set windowed mode and the resolution in retroarch too 720x480. What do you think?

Honestly I am not sure, I have never had any issues with 720p on my TV and AFAIK nobody has reported any critical issues either. I can only test this on my 1080p TV that can have resolution down to 480p, but like I said I never had any issues before, so I leave it up to you.

**Comment by Langerz82** [comment]
ok man. I will add the PR's separately. I will add them now but please don't commit as I will test them thoroughly.
What I'm worried about in setting 720x480 to 480p in sys/class/display is that it might corrupt handheld displays that actually use 720x480. Maybe we just add it, and if people report 720x480 to 480p giving them probs we change it. In theory it shouldn't be an issue but I dont have a handheld to check on.

**Comment by shantigilbert** [comment]
> 
> 
> ok man. I will add the PR's separately. I will add them now but please don't commit as I will test them thoroughly.
> What I'm worried about in setting 720x480 to 480p in sys/class/display is that it might corrupt handheld displays that actually use 720x480. Maybe we just add it, and if people report 720x480 to 480p giving them probs we change it. In theory it shouldn't be an issue but I dont have a handheld to check on.

What does this change fix? 

can't you just add a if...then?

**Comment by dankcushions** [comment]
> ok man. I will add the PR's separately. I will add them now but please don't commit as I will test them thoroughly.

you should use github’s draft PR function: https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by Langerz82** [comment]
It adds allot more support for various resolutions. I removed the 720x480 to 480p as it was a hack. These changes are much more clean and support allot more different res's as emulationstation detects various resolutions others can use.

**Pull request closed without merging**
