### PR TITLE
zlib and kernel update

### PR DESCRIPTION
**Pull request by Shin8K**
zlib update to 1.2.13
kernel update to 20221012

### CODE REVIEW

**Comment by shantigilbert** [comment]
To do what exactly?

**Comment by Shin8K** [comment]
> To do what exactly?

I got a complie error, cos the zlib 1.2.12 is no longer exist on the server.

**Comment by shantigilbert** [comment]
And why is the firmware needed to update?

**Comment by Shin8K** [comment]
firmware is not a nessesary update. i got this download failed, so i updated this Incidentally.
I'm still compiling, the TvTextViewer is out of date too, the latest version is a01d9c23db92b0757b3e9b1ff11e040337d945c3

**Comment by Shin8K** [comment]
firmware is not a nessesary update. i got this download failed, so i updated this Incidentally.
I'm still compiling, the TvTextViewer is out of date too, the latest version is a01d9c23db92b0757b3e9b1ff11e040337d945c3

**Comment by shantigilbert** [comment]
Please do not open PRs like this, just update one thing at a time, when it's absolutely necessary.

**Pull request closed without merging**
