### PR TITLE
Dev mupen64plussa resolution

### PR DESCRIPTION
**Pull request by Langerz82**
Sets the mupen64plus standalone resolution determined by the current video mode.

### CODE REVIEW

**Comment by Langerz82** [comment]
Apologies on the amount of commits, when this is commited. I'll remove my build and start on a new copy.

**Comment by Langerz82** [comment]
Tested, ready for commit.

**Comment by shantigilbert** [comment]
Was this actually tested on handhelds?

**Comment by Langerz82** [comment]
It should work ok on handhelds too, but no I have not tested on handhelds. As long as the device supports the selected resolution nativevideo or default res it should too.

**Comment by shantigilbert** [comment]
> It should work ok on handhelds too, but no I have not tested on handhelds. As long as the device supports the selected resolution nativevideo or default res it should too.

I am not sure about that, handhelds use a different video back-end not sure if `/sys/class/display/mode` even exists. So I (or someone else ) need to test this on handhelds first, reason being is that you marked this as a fix for #814 without proper testing.

**Comment by shantigilbert** [comment]
> Just tested it on the OGS, it does not work. /sys/class/display does not exist on handhelds, so it still starts with video mode 1920x1080.

Thank you, I suspected that was the issue... need to find a workaround for resolution

maybe we can use the `EE_DEVICE` variable to set up hard-coded resolutions for the handhelds.

**Comment by shantigilbert** [comment]
@miwasp can you try adding this to line 11 of m64p.sh?

```
  case "$(oga_ver)" in
    "OGA"*)
        echo "480 320"
        return 0
    ;;
    "OGS")
        echo "854 480"
        return 0
    ;;
    "GF")
        echo "640 480" 
        return 0
    ;;
        esac
```

**Comment by shantigilbert** [comment]
Thanks, I will add a separate commit for the fix

**Comment by shantigilbert** [comment]
Done, it should work now for all devices

**Pull request merged**
