### PR TITLE
Support for mods with doom similar to ECWolf

### PR DESCRIPTION
**Pull request by miwasp**
This works really good but somehow 'breaks' the usage of libretro prboom. I had to copy the wad, iwad, pwad files to the subdir games. This way at least those still work with prboom. Calling .choco files with prboom gives an error.

### CODE REVIEW

**Comment by shantigilbert** [comment]
This can work but there are some issue I would like to resolve first.

1.- Is there really a need to create the `games` folder? 
2.- Copying the .wad files is not ideal, need to figure out the root of the cause with prboom
3.- What is in a typical .choco file?

**Comment by miwasp** [comment]
1. In doom most of the mods are itself wad-files. If you put those mods in subdirs under roms/ports/doom they will show up in ES. So i think yes, there is a need for the games folder.
2. Yes, copying is not ideal. Since the games folder has to be set as path in es_systems.cfg (see 1.) prboom looks for the wads (or iwads or pwads) in this folder. If there is another way to tell prboom to look for those wads in roms/ports/doom then there would be no need for copying.
If a .choco file is selected and prboom is set as core, is there any possibility to pop up a message as this will not work?
3. Typical .choco files look like this:
GAMETYPE=doom
SUBDIR=
PARAMS=-iwad /storage/roms/ports/doom/chex/chex.wad -deh /storage/roms/ports/doom/chex/chex.deh
or
GAMETYPE=strife
SUBDIR=
PARAMS=-iwad /storage/roms/ports/doom/strife/strife1.wad
or
GAMETYPE=doom
SUBDIR=
PARAMS=-iwad /storage/roms/ports/doom/doom2/Doom2.wad -merge /storage/roms/ports/doom/Doom64_for_Doom2/D64D2.wad -deh /storage/roms/ports/doom/Doom64_for_Doom2/d64d2.deh

I'm not sure, if "SUBDIR" is really needed in .choco files. All the mods i have here don't need it, but there are likely mods that need to run in a specific dir.

**Comment by shantigilbert** [comment]
Are the wads self contained? or do they depend on the original wad? 

Just from your text (I have not tested it) can't it be done like this:

Create /storage/roms/ports/doom_mods (or something like that) and all the .wads and other mod files go here then a .chocho file can then point the  params to that folder.  This way no files are copied, nor do we need to worry folders inside the doom folder, and it does not break support for pr_boom.

**Comment by miwasp** [comment]
Those wads typically depend on the original wad.

The part with doom_mods would work but then you still have one problem:
You have a mixed list of wads and .choco files in ES then but .choco files don‘t work with prboom. Some kind of error must be displayed. Without any further actions prboom would be started with the choco file and errors out.

**Comment by shantigilbert** [comment]
I think people that add choco files should already know that they need to change the emulator. Or a default can be set in emuelec.conf for chocho files

**Comment by miwasp** [comment]
Afaik the.default emulator for doom is already chocolate-doom.

I just had a look in emuelec.conf. How can i set a default for choco files in there?

**Comment by shantigilbert** [comment]
I am mistaken, it can't be per extension.

But if ChocoDOOM is already the default, then we should not worry about pr_boom, like I Said people making the .chocho files should know that they do not work with pr_boom.

I am more worried about copying files around and creating more clutter than needed.

**Comment by miwasp** [comment]
Ok, i will test that later today.

**Comment by miwasp** [comment]
I also have added wiki pages for ecwolf and chocolate-doom. I hope, this is ok.

**Pull request merged**
