### PR TITLE
Multiple controller mappings - iNNEXT USB and PlayGame USB

### PR DESCRIPTION
**Pull request by nwildner**
Hi :)
Both are USB clone controllers, one of them is a SNES-Alike USB from iNNEXT, the other one, PlayGame PS2-Alike USB

- iNNEXT: - https://www.youtube.com/watch?v=v7KYR5HAQBc

image

- PlayGame(which could be a rebrand of a more generic controller like Fox):

image

### CODE REVIEW

**Comment by shantigilbert** [comment]
Thanks, you also need to provide the settings for the `gamecontrollerdb.txt` https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/tools/sysutils/SDL_GameControllerDB/patches/add-emuelec-gamepads.patch#L7

Change `@@ -1,5 +1,14 @@` to `@@ -1,5 +1,16 @@`
add 2 more lines to the patch with the data `+yourcontrollerinfo...` this data should already be in your `/storage/.config/SDL-GameControllerDB/gamecontrollerdb.txt`

**Comment by nwildner** [comment]
done @shantigilbert  :)

(and taken note for the next controller contributions as well)

**Comment by nwildner** [comment]
just as additional information: in today's morning, I've received my 8BitDo SN30 pro from mail, and also added this controller as well to EmuELEC database @shantigilbert , thus why SDL gamecontrollerdb is `@@ -1,5 +1,17 @@` not `@@ -1,5 +1,16 @@` :)

**Comment by shantigilbert** [comment]
@nwildner Since I've changed how SDL works, I need to release a new test for your to make sure these changes work, so I will put this on hold until that is done if that is OK with you.

**Comment by nwildner** [comment]
Sounds good @shantigilbert :)

**Comment by shantigilbert** [comment]
> Sounds good @shantigilbert :)

Can you test this on v4.4 just to make sure they work as they should?

**Comment by nwildner** [comment]
> > Sounds good @shantigilbert :)
> 
> Can you test this on v4.4 just to make sure they work as they should?

You mean, providing this very same configuration manually, or by cleaning up my current configs and upgrading to 4.4

I'll upgrade my box here meanwhile.

**Comment by nwildner** [comment]
Hi @shantigilbert 

4.4 does not seems to have this patch merged (yet) but I've copied those configs manually to my box and they worked.

Have a nice week.

**Comment by shantigilbert** [comment]
> Hi @shantigilbert
> 
> 4.4 does not seems to have this patch merged (yet) but I've copied those configs manually to my box and they worked.
> 
> Have a nice week.

I was waiting for your confirmation. since I mentioned that the input handling was changed I wanted to make sure these worked.

**Pull request merged**
