### PR TITLE
update kernel-firmware 20240811

### PR DESCRIPTION
**Pull request by Kelvfimer**
This pull request includes an update to the `kernel-firmware` package version and its associated SHA256 checksum.

* Updated `PKG_VERSION` to `20240811` in `packages/linux-firmware/kernel-firmware/package.mk`.
* Updated `PKG_SHA256` to `d845252e0b0ce2f5dfabc22926cd70a939993329dc1b0c33ffc0c802f27c4e10` in `packages/linux-firmware/kernel-firmware/package.mk`.

### CODE REVIEW

**Comment by miwasp** [comment]
> 2024-12-08 00:58:17 (25.1 MB/s) - '/xxx/EmuELEC/sources/kernel-firmware/kernel-firmware-20240811.tar.xz' saved [379287388/379287388]
> 
>     WARNING      Incorrect checksum calculated on downloaded file: got 58f1a14b800e3d1967986197d83c81f1ad14b7898a557133c58df0c02c538082 wanted d845252e0b0ce2f5dfabc22926cd70a939993329dc1b0c33ffc0c802f27c4e10
>

**Comment by miwasp** [comment]
The package "rdfind" needs to be installed on the host now. This was not necessary before this PR.

**Comment by Kelvfimer** [comment]
Yes it is needed to be installed @miwasp

**Comment by shantigilbert** [comment]
If a new pacakge is required, please update README.md to reflect this.

**Comment by Kelvfimer** [comment]
I will @shantigilbert 

@miwasp The sha2 that I have it's the one that I commited. I retested and remains the same . How did you get that one? thx

imagen

**Comment by Kelvfimer** [comment]
done update of readme @shantigilbert

**Comment by miwasp** [comment]
My build system downloads "https://cdn.kernel.org/pub/linux/kernel/firmware/linux-firmware-20240811.tar.xz" and this
has a SHA256 of "58F1A14B800E3D1967986197D83C81F1AD14B7898A557133C58DF0C02C538082".

**Comment by Kelvfimer** [comment]
If @shantigilbert can check

**Comment by Kelvfimer** [comment]
@miwasp strange I created a new Emuelec folder for building from scratch and the SHA2 is as yours. I will update it to 58f1a14b800e3d1967986197d83c81f1ad14b7898a557133c58df0c02c538082

**Comment by Kelvfimer** [comment]
updated ready to merge @shantigilbert

**Pull request merged**
