### PR TITLE
Dev advmame joy update

### PR DESCRIPTION
**Pull request by Langerz82**
AdvMame joy update for compatibility with more controllers like Arcade Controllers.
1. Should now enable proper Joypad config names for Advmame.
2. Create file in /storage/.config/JP_ADVMAME_INVERT_AXIS to invert the left axis values for x, and y. e.g.
```
touch /storage/.config/JP_ADVMAME_INVERT_AXIS
```

Testing:
To test simply copy both modified files in /emuelec/bin then give them exec permissions with (chmod +x filename), then run set_advmame.joy with "./set_advmame_joy.sh".

### CODE REVIEW

**Comment by kwatkins** [comment]
This works! The buttons do at least. I am noticing that the joystick controls are reversed: down = right, up = left, left = up, right = n/a

**Comment by Langerz82** [comment]
did you create the file in /storage/.config/JP_ADVMAME_INVERT_AXIS ? It's an empty file and will invert the axis if present.

**Comment by kwatkins** [comment]
@Langerz82 ugh sorry my bad wow not reading things clearly today apparently :) - that did the trick. this change looks gtg from my end.

**Comment by Langerz82** [comment]
can commit.

**Pull request merged**
