### PR TITLE
Quirk for initialization of Shanwan DS3 clones.  

### PR DESCRIPTION
**Pull request by lbernstone**
Prevents continuous rumble on USB connection.  These gamepads are available dirt cheap on aliexpress.com.

### CODE REVIEW

**Comment by shantigilbert** [comment]
Thank you!

**Comment by shantigilbert** [comment]
@lbernstone Is there a possibility this could be implemented for S905 devices as well? (Kernel 3.14)

**Comment by SumavisionQ5** [comment]
@lbernstone Thanks for it. BTW, can you get rumble working for Shanwan DS3 controller over USB? And rumble does not work properly over BT for Shanwan DS3 controller.

**Comment by SumavisionQ5** [comment]
ttps://github.com/RetroPie/RetroPie-Setup/pull/2263/commits/017f00f6e15f04b3272ff1abae8742dc4c47b608

gasia PS3 clone pad needs similar fix, too.

**Pull request merged**
